"""Executed behaviour for migration 093 and the capability projector.

Run with ``RUN_POSTGRES_INTEGRATION_TESTS=1``. Uses a disposable Postgres
container and never connects to a configured environment.

The source-contract tests in `test_capability_phase1.py` prove the SQL *says*
the right thing. These prove it *does* the right thing, which is a different
claim and the only one that settles: a cardinality violation on colliding
rules, whether a column-level grant actually blocks an UPDATE, whether a
disabled source really leaves the effective view, and whether withdrawal to
zero is distinguishable from a failed load.
"""

from __future__ import annotations

import os
import re
from pathlib import Path
from urllib.parse import urlparse

import psycopg
import pytest

# A normal import, deliberately not importorskip: these tests only run when
# PostgreSQL integration is explicitly enabled, and an import regression in the
# projector must fail loudly rather than silently skipping the guard tests that
# are the whole point of this module.
from ingest.intel import capability_match

_MIGRATION = (
    Path(__file__).resolve().parents[2]
    / "sql" / "migrations" / "093_capability_assertions.sql"
)

_ROLE_PASSWORD = "probe"  # noqa: S105 - disposable container, not a secret


# ── Minimal 074/076-compatible fixture ──────────────────────────────────────
#
# NOT the full migration chain through 092: only the objects 093 references --
# the catalog schema, publishers/products with the product_uuid unique key from
# 076, the four runtime roles, and 074's default privileges. So these tests
# prove 093 is self-consistent against its stated dependencies, not that it
# applies cleanly on top of production's actual accumulated schema. Only a
# rehearsal against a real chain can show that.

_PRIOR_SCHEMA = """
CREATE SCHEMA catalog;

CREATE TABLE catalog.publishers (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canonical_name text NOT NULL
);

CREATE TABLE catalog.products (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publisher_id   bigint REFERENCES catalog.publishers (id),
    canonical_name text NOT NULL,
    product_uuid   uuid NOT NULL DEFAULT gen_random_uuid()
);
ALTER TABLE catalog.products
    ADD CONSTRAINT uq_catalog_products_uuid UNIQUE (product_uuid);

GRANT USAGE ON SCHEMA catalog
    TO operations_app, operations_readonly, metabase_ro, ninja_ingest;
GRANT SELECT ON ALL TABLES IN SCHEMA catalog
    TO operations_app, operations_readonly, metabase_ro, ninja_ingest;

-- 074 sets this, and 093 relies on it for read access to its new tables.
ALTER DEFAULT PRIVILEGES IN SCHEMA catalog
    GRANT SELECT ON TABLES TO operations_app, operations_readonly, metabase_ro;
"""


@pytest.fixture(scope="module")
def pg():
    if os.environ.get("RUN_POSTGRES_INTEGRATION_TESTS") != "1":
        pytest.skip(
            "set RUN_POSTGRES_INTEGRATION_TESTS=1 to start a disposable Postgres container"
        )
    postgres = pytest.importorskip("testcontainers.postgres")
    container = postgres.PostgresContainer("postgres:16-alpine")
    with container:
        url = urlparse(
            container.get_connection_url().replace("postgresql+psycopg2://", "postgresql://")
        )
        admin_dsn = (
            f"postgresql://{url.username}:{url.password}@{url.hostname}:{url.port}"
            f"{url.path}"
        )

        def role_dsn(role: str) -> str:
            return (
                f"postgresql://{role}:{_ROLE_PASSWORD}@{url.hostname}:{url.port}{url.path}"
            )

        with psycopg.connect(admin_dsn, autocommit=True) as conn, conn.cursor() as cur:
            for role in (
                "operations_app", "operations_readonly", "metabase_ro", "ninja_ingest"
            ):
                # DDL takes no bind parameters; the value is a fixed constant
                # for a disposable container, not a credential.
                cur.execute(
                    f"CREATE ROLE {role} LOGIN PASSWORD '{_ROLE_PASSWORD}'"
                )
                cur.execute(
                    f"GRANT CONNECT ON DATABASE {url.path.lstrip('/')} TO {role}"
                )
            cur.execute(_PRIOR_SCHEMA)
            # Applying 093 here is itself the applicability check: if it is not
            # applicable to this fixture, every test in the module errors here
            # rather than reporting a misleading pass. Scope caveat above.
            cur.execute(_MIGRATION.read_text(encoding="utf-8"))

        yield {"admin": admin_dsn, "role_dsn": role_dsn}


@pytest.fixture(autouse=True)
def clean(pg):
    """Each test starts from an empty corpus but the same schema."""
    with psycopg.connect(pg["admin"], autocommit=True) as conn, conn.cursor() as cur:
        cur.execute("DELETE FROM catalog.capability_assertion_machine")
        cur.execute("DELETE FROM catalog.capability_assertion_operator")
        cur.execute("DELETE FROM catalog.capability_rule")
        cur.execute("UPDATE catalog.capability_source SET enabled = TRUE")
        cur.execute("DELETE FROM catalog.products")
        cur.execute("DELETE FROM catalog.publishers")


# ── helpers ─────────────────────────────────────────────────────────────────

def _product(cur, name: str, publisher: str | None = None) -> str:
    pub_id = None
    if publisher is not None:
        cur.execute(
            "INSERT INTO catalog.publishers (canonical_name) VALUES (%s) RETURNING id",
            (publisher,),
        )
        pub_id = cur.fetchone()[0]
    cur.execute(
        "INSERT INTO catalog.products (publisher_id, canonical_name) "
        "VALUES (%s, %s) RETURNING product_uuid",
        (pub_id, name),
    )
    return cur.fetchone()[0]


def _rule(cur, key: str, capability: str, *, title="", publisher="",
          source="vetted_rule", priority=100, enabled=True) -> None:
    cur.execute(
        "INSERT INTO catalog.capability_rule "
        "(rule_key, capability, title_pattern, publisher_pattern, source_key, "
        " priority, enabled) VALUES (%s,%s,%s,%s,%s,%s,%s)",
        (key, capability, title, publisher, source, priority, enabled),
    )


def _project(dsn: str) -> tuple[int, int, int, list[str]]:
    """Run the real projector against the disposable container.

    One execution path: these tests drive `project_with_cursor` itself rather
    than a copy of its SQL, so a change to the projector cannot pass here while
    breaking in production.

    Not autocommit: `_COMPUTE_SQL` builds a TEMP TABLE ... ON COMMIT DROP, so
    every statement committing on its own would drop it before the write.
    """
    with psycopg.connect(dsn) as conn, conn.cursor() as cur:
        result = capability_match.project_with_cursor(cur)
        conn.commit()
    return result


def _effective(cur, product_uuid: str) -> list[tuple]:
    cur.execute(
        "SELECT capability, state, alertable FROM "
        "catalog.v_product_capability_effective WHERE product_uuid = %s "
        "ORDER BY capability",
        (product_uuid,),
    )
    return cur.fetchall()


# ── migration applicability ─────────────────────────────────────────────────

def test_migration_created_every_object(pg) -> None:
    with psycopg.connect(pg["admin"], autocommit=True) as conn, conn.cursor() as cur:
        for table in (
            "capability", "capability_source", "capability_rule",
            "capability_assertion_machine", "capability_assertion_operator",
        ):
            cur.execute("SELECT to_regclass(%s)", (f"catalog.{table}",))
            assert cur.fetchone()[0] is not None, table
        cur.execute("SELECT to_regclass('catalog.v_product_capability_effective')")
        assert cur.fetchone()[0] is not None
        cur.execute("SELECT count(*) FROM catalog.capability")
        assert cur.fetchone()[0] == 3


def test_migration_is_idempotent(pg) -> None:
    """Re-running must not fail: the runner records versions, but a partial
    failure elsewhere should not make this file un-rerunnable."""
    with psycopg.connect(pg["admin"], autocommit=True) as conn, conn.cursor() as cur:
        cur.execute(_MIGRATION.read_text(encoding="utf-8"))
        cur.execute("SELECT count(*) FROM catalog.capability_source")
        assert cur.fetchone()[0] == 5


# ── projector behaviour ─────────────────────────────────────────────────────

def test_colliding_rules_collapse_deterministically(pg) -> None:
    """Two rules matching one product previously raised
    'ON CONFLICT DO UPDATE command cannot affect row a second time'."""
    with psycopg.connect(pg["admin"], autocommit=True) as conn, conn.cursor() as cur:
        uuid_ = _product(cur, "acme remote desktop", "Acme Ltd")
        # Same specificity, different priority -> lower priority number wins.
        _rule(cur, "b_low_priority", "remote_access", title="acme remote%", priority=50)
        _rule(cur, "a_high_priority", "remote_access", title="acme remote desktop", priority=10)

    _project(pg["admin"])

    with psycopg.connect(pg["admin"], autocommit=True) as conn, conn.cursor() as cur:
        cur.execute(
            "SELECT evidence_ref, count(*) OVER () FROM "
            "catalog.capability_assertion_machine WHERE product_uuid = %s "
            "AND withdrawn_at IS NULL", (uuid_,),
        )
        rows = cur.fetchall()
    assert len(rows) == 1, "collision must collapse to one current row"
    assert rows[0][0] == "a_high_priority", "lowest priority number wins"


def test_specificity_beats_priority(pg) -> None:
    with psycopg.connect(pg["admin"], autocommit=True) as conn, conn.cursor() as cur:
        uuid_ = _product(cur, "acme rmm agent", "Acme Ltd")
        _rule(cur, "title_only", "rmm", title="acme rmm%", priority=1)
        _rule(cur, "title_and_pub", "rmm", title="acme rmm%",
              publisher="Acme%", priority=900)

    _project(pg["admin"])

    with psycopg.connect(pg["admin"], autocommit=True) as conn, conn.cursor() as cur:
        cur.execute(
            "SELECT evidence_ref, evidence_kind, confidence FROM "
            "catalog.capability_assertion_machine WHERE product_uuid = %s",
            (uuid_,),
        )
        ref, kind, conf = cur.fetchone()
    assert ref == "title_and_pub"
    assert kind == "rule.title+publisher"
    assert float(conf) == 0.95


def test_projection_is_state_idempotent_not_write_free(pg) -> None:
    """State-idempotent, deliberately not write-free.

    The upsert's DO UPDATE always fires, refreshing `last_observed_at`, so a
    second run reports 1 written rather than 0. That refresh is the record that
    the evidence is still supported, which is what makes a later withdrawal
    meaningful -- so the write is wanted. What must not change is the row count
    or `first_observed_at`: a re-observation is not a new observation.
    """
    with psycopg.connect(pg["admin"], autocommit=True) as conn, conn.cursor() as cur:
        _product(cur, "acme control", "Acme Ltd")
        _rule(cur, "acme", "remote_access", title="acme control")

    _project(pg["admin"])
    with psycopg.connect(pg["admin"], autocommit=True) as conn, conn.cursor() as cur:
        cur.execute("SELECT first_observed_at FROM catalog.capability_assertion_machine")
        first = cur.fetchone()[0]

    written, withdrawn, _, _ = _project(pg["admin"])

    with psycopg.connect(pg["admin"], autocommit=True) as conn, conn.cursor() as cur:
        cur.execute(
            "SELECT count(*), min(first_observed_at), max(last_observed_at) FROM "
            "catalog.capability_assertion_machine WHERE withdrawn_at IS NULL"
        )
        count, still, last_seen = cur.fetchone()
    assert count == 1, "no duplicate row"
    assert still == first, "a re-observation is not a new observation"
    assert withdrawn == 0
    assert written == 1, (
        "the upsert refreshes last_observed_at, so a second run updates rather "
        "than writing nothing -- state-idempotent, not write-free"
    )
    assert last_seen >= first


def test_zero_match_evaluation_withdraws_with_a_reason(pg) -> None:
    """A source whose rules stop matching must withdraw, or it asserts a
    capability no rule supports, forever."""
    with psycopg.connect(pg["admin"], autocommit=True) as conn, conn.cursor() as cur:
        uuid_ = _product(cur, "acme control", "Acme Ltd")
        _rule(cur, "acme", "remote_access", title="acme control")
    _project(pg["admin"])

    # Rule still loads, but now matches nothing.
    with psycopg.connect(pg["admin"], autocommit=True) as conn, conn.cursor() as cur:
        cur.execute(
            "UPDATE catalog.capability_rule SET title_pattern = 'nothing matches this'"
        )

    _, withdrawn, _, _ = _project(pg["admin"])

    assert withdrawn == 1
    with psycopg.connect(pg["admin"], autocommit=True) as conn, conn.cursor() as cur:
        cur.execute(
            "SELECT withdrawn_at, withdrawn_reason FROM "
            "catalog.capability_assertion_machine WHERE product_uuid = %s", (uuid_,)
        )
        at, reason = cur.fetchone()
        assert at is not None
        assert "no longer matched" in reason
        assert _effective(cur, uuid_) == []


def test_empty_rule_set_preserves_prior_assertions(pg) -> None:
    """A rule table that failed to load looks exactly like one matching
    nothing. Treating them alike would withdraw the whole corpus.

    This drives the projector's real control flow -- asserting the guard's
    *condition* would not prove it takes the branch.
    """
    with psycopg.connect(pg["admin"], autocommit=True) as conn, conn.cursor() as cur:
        uuid_ = _product(cur, "acme control", "Acme Ltd")
        _rule(cur, "acme", "remote_access", title="acme control")
    _project(pg["admin"])

    with psycopg.connect(pg["admin"], autocommit=True) as conn, conn.cursor() as cur:
        cur.execute("DELETE FROM catalog.capability_rule")

    # The real guard, executed.
    with psycopg.connect(pg["admin"]) as conn, conn.cursor() as cur:
        written, withdrawn, rules, evaluated = capability_match.project_with_cursor(cur)
        conn.commit()

    assert (written, withdrawn, rules, evaluated) == (0, 0, 0, []), (
        "an empty rule set must return without touching anything"
    )

    with psycopg.connect(pg["admin"], autocommit=True) as conn, conn.cursor() as cur:
        cur.execute(
            "SELECT count(*) FROM catalog.capability_assertion_machine "
            "WHERE withdrawn_at IS NULL AND product_uuid = %s", (uuid_,)
        )
        assert cur.fetchone()[0] == 1, "prior evidence must survive"
        assert _effective(cur, uuid_) == [("remote_access", "asserted", True)]


def test_loaded_rules_that_match_nothing_do_withdraw(pg) -> None:
    """The other side of the guard, also through the real control flow: a
    source whose rules loaded but matched nothing is a real answer."""
    with psycopg.connect(pg["admin"], autocommit=True) as conn, conn.cursor() as cur:
        uuid_ = _product(cur, "acme control", "Acme Ltd")
        _rule(cur, "acme", "remote_access", title="acme control")
    _project(pg["admin"])

    with psycopg.connect(pg["admin"], autocommit=True) as conn, conn.cursor() as cur:
        cur.execute(
            "UPDATE catalog.capability_rule SET title_pattern = 'matches nothing'"
        )

    with psycopg.connect(pg["admin"]) as conn, conn.cursor() as cur:
        written, withdrawn, rules, evaluated = capability_match.project_with_cursor(cur)
        conn.commit()

    assert rules == 1
    assert evaluated == ["vetted_rule"], "a loaded source counts as evaluated"
    assert withdrawn == 1
    with psycopg.connect(pg["admin"], autocommit=True) as conn, conn.cursor() as cur:
        assert _effective(cur, uuid_) == []


# ── effective view precedence ───────────────────────────────────────────────

def _seed_machine(cur, uuid_: str, capability: str, source: str) -> None:
    cur.execute(
        "INSERT INTO catalog.capability_assertion_machine "
        "(product_uuid, capability, source_key, confidence, evidence_kind, "
        " matcher_version) VALUES (%s,%s,%s,0.9,'test','t')",
        (uuid_, capability, source),
    )


def test_disabled_source_disappears_from_effective(pg) -> None:
    with psycopg.connect(pg["admin"], autocommit=True) as conn, conn.cursor() as cur:
        uuid_ = _product(cur, "acme control")
        _seed_machine(cur, uuid_, "remote_access", "vetted_rule")
        assert _effective(cur, uuid_) == [("remote_access", "asserted", True)]

        cur.execute(
            "UPDATE catalog.capability_source SET enabled = FALSE "
            "WHERE source_key = 'vetted_rule'"
        )
        assert _effective(cur, uuid_) == [], (
            "disabling must remove evidence, not downgrade it to a candidate"
        )


def test_operator_negative_overrides_alertable_machine(pg) -> None:
    with psycopg.connect(pg["admin"], autocommit=True) as conn, conn.cursor() as cur:
        uuid_ = _product(cur, "acme control")
        _seed_machine(cur, uuid_, "remote_access", "vetted_rule")
        cur.execute(
            "INSERT INTO catalog.capability_assertion_operator "
            "(product_uuid, capability, polarity, confirmed_by) "
            "VALUES (%s,'remote_access',FALSE,'curator')", (uuid_,),
        )
        assert _effective(cur, uuid_) == [("remote_access", "refuted", False)]


def test_operator_positive_promotes_candidate_only_evidence(pg) -> None:
    with psycopg.connect(pg["admin"], autocommit=True) as conn, conn.cursor() as cur:
        uuid_ = _product(cur, "acme control")
        _seed_machine(cur, uuid_, "remote_access", "chocolatey_tag")
        assert _effective(cur, uuid_) == [("remote_access", "candidate", False)]

        cur.execute(
            "INSERT INTO catalog.capability_assertion_operator "
            "(product_uuid, capability, polarity, confirmed_by) "
            "VALUES (%s,'remote_access',TRUE,'curator')", (uuid_,),
        )
        assert _effective(cur, uuid_) == [("remote_access", "confirmed", True)]


def test_withdrawn_operator_evidence_restores_machine_result(pg) -> None:
    with psycopg.connect(pg["admin"], autocommit=True) as conn, conn.cursor() as cur:
        uuid_ = _product(cur, "acme control")
        _seed_machine(cur, uuid_, "remote_access", "vetted_rule")
        cur.execute(
            "INSERT INTO catalog.capability_assertion_operator "
            "(product_uuid, capability, polarity, confirmed_by) "
            "VALUES (%s,'remote_access',FALSE,'curator')", (uuid_,),
        )
        assert _effective(cur, uuid_) == [("remote_access", "refuted", False)]

        cur.execute(
            "UPDATE catalog.capability_assertion_operator "
            "SET withdrawn_at = now(), withdrawn_reason = 'reassessed'"
        )
        assert _effective(cur, uuid_) == [("remote_access", "asserted", True)]


def test_unknown_produces_no_effective_row(pg) -> None:
    with psycopg.connect(pg["admin"], autocommit=True) as conn, conn.cursor() as cur:
        uuid_ = _product(cur, "entirely unremarkable tool")
        assert _effective(cur, uuid_) == [], "absence must be absence, not 'safe'"


# ── constraints ─────────────────────────────────────────────────────────────

def test_machine_cannot_reference_an_operator_source(pg) -> None:
    with psycopg.connect(pg["admin"], autocommit=True) as conn, conn.cursor() as cur:
        uuid_ = _product(cur, "acme control")
        with pytest.raises(psycopg.errors.ForeignKeyViolation):
            _seed_machine(cur, uuid_, "remote_access", "operator")


@pytest.mark.parametrize(
    "kwargs",
    [
        {"title": "%chrome"},                      # leading % wildcard
        {"title": "_hrome"},                       # leading _ wildcard
        {"publisher": "%acme"},
        {"publisher": "_cme"},
        {"title": "", "publisher": ""},            # no pattern at all
        {"title": "", "publisher": "acme%", "source": "vetted_rule"},  # vetted w/o title
        {"title": "chrome", "source": "lolrmm"},   # unrelated source
        {"title": "chrome", "source": "chocolatey_tag"},
    ],
)
def test_invalid_rules_are_rejected(pg, kwargs) -> None:
    with psycopg.connect(pg["admin"], autocommit=True) as conn, conn.cursor() as cur:
        with pytest.raises(psycopg.errors.Error):
            _rule(cur, "bad_rule", "rmm", **kwargs)


def test_source_cannot_promote_itself_to_alerting(pg) -> None:
    with psycopg.connect(pg["admin"], autocommit=True) as conn, conn.cursor() as cur:
        with pytest.raises(psycopg.errors.CheckViolation):
            cur.execute(
                "UPDATE catalog.capability_source SET may_alert = TRUE "
                "WHERE source_key = 'chocolatey_tag'"
            )


def test_withdrawal_requires_a_reason(pg) -> None:
    with psycopg.connect(pg["admin"], autocommit=True) as conn, conn.cursor() as cur:
        uuid_ = _product(cur, "acme control")
        _seed_machine(cur, uuid_, "remote_access", "vetted_rule")
        with pytest.raises(psycopg.errors.CheckViolation):
            cur.execute(
                "UPDATE catalog.capability_assertion_machine SET withdrawn_at = now()"
            )


# ── uniqueness and history ──────────────────────────────────────────────────

def test_current_row_uniqueness_and_withdraw_reinsert_history(pg) -> None:
    with psycopg.connect(pg["admin"], autocommit=True) as conn, conn.cursor() as cur:
        uuid_ = _product(cur, "acme control")
        _seed_machine(cur, uuid_, "remote_access", "vetted_rule")
        with pytest.raises(psycopg.errors.UniqueViolation):
            _seed_machine(cur, uuid_, "remote_access", "vetted_rule")

        cur.execute(
            "UPDATE catalog.capability_assertion_machine "
            "SET withdrawn_at = now(), withdrawn_reason = 'gone'"
        )
        _seed_machine(cur, uuid_, "remote_access", "vetted_rule")
        cur.execute(
            "SELECT count(*) FROM catalog.capability_assertion_machine "
            "WHERE product_uuid = %s", (uuid_,)
        )
        assert cur.fetchone()[0] == 2, "both episodes must remain visible"


def test_operator_uniqueness_and_history(pg) -> None:
    with psycopg.connect(pg["admin"], autocommit=True) as conn, conn.cursor() as cur:
        uuid_ = _product(cur, "acme control")
        insert = (
            "INSERT INTO catalog.capability_assertion_operator "
            "(product_uuid, capability, polarity, confirmed_by) "
            "VALUES (%s,'rmm',TRUE,'curator')"
        )
        cur.execute(insert, (uuid_,))
        with pytest.raises(psycopg.errors.UniqueViolation):
            cur.execute(insert, (uuid_,))
        cur.execute(
            "UPDATE catalog.capability_assertion_operator "
            "SET withdrawn_at = now(), withdrawn_reason = 'reassessed'"
        )
        cur.execute(insert, (uuid_,))
        cur.execute("SELECT count(*) FROM catalog.capability_assertion_operator")
        assert cur.fetchone()[0] == 2


# ── grants ──────────────────────────────────────────────────────────────────

def test_operations_cannot_write_machine_evidence(pg) -> None:
    with psycopg.connect(pg["admin"], autocommit=True) as conn, conn.cursor() as cur:
        uuid_ = _product(cur, "acme control")
        _seed_machine(cur, uuid_, "remote_access", "vetted_rule")

    with psycopg.connect(pg["role_dsn"]("operations_app"), autocommit=True) as conn:
        with conn.cursor() as cur:
            cur.execute("SELECT count(*) FROM catalog.capability_assertion_machine")
            assert cur.fetchone()[0] == 1  # reading is allowed
        for sql in (
            "INSERT INTO catalog.capability_assertion_machine "
            "(product_uuid, capability, source_key, confidence, evidence_kind, "
            " matcher_version) VALUES (%s,'rmm','vetted_rule',0.9,'x','t')",
            "UPDATE catalog.capability_assertion_machine SET confidence = 0.1",
            "DELETE FROM catalog.capability_assertion_machine",
        ):
            with conn.cursor() as cur, pytest.raises(psycopg.errors.InsufficientPrivilege):
                cur.execute(sql, (uuid_,) if "%s" in sql else None)


def test_operations_may_insert_operator_evidence_but_only_withdraw_it(pg) -> None:
    with psycopg.connect(pg["admin"], autocommit=True) as conn, conn.cursor() as cur:
        uuid_ = _product(cur, "acme control")

    with psycopg.connect(pg["role_dsn"]("operations_app"), autocommit=True) as conn:
        with conn.cursor() as cur:
            cur.execute(
                "INSERT INTO catalog.capability_assertion_operator "
                "(product_uuid, capability, polarity, confirmed_by) "
                "VALUES (%s,'rmm',TRUE,'curator')", (uuid_,),
            )
        # Withdrawal fields are permitted.
        with conn.cursor() as cur:
            cur.execute(
                "UPDATE catalog.capability_assertion_operator "
                "SET withdrawn_at = now(), withdrawn_reason = 'reassessed'"
            )
        # A conclusion is history: rewriting it in place must fail.
        for column, value in (
            ("polarity", "FALSE"),
            ("confirmed_by", "'someone else'"),
            ("capability", "'remote_access'"),
        ):
            with conn.cursor() as cur, pytest.raises(psycopg.errors.InsufficientPrivilege):
                cur.execute(
                    f"UPDATE catalog.capability_assertion_operator SET {column} = {value}"
                )


def test_ingest_role_boundaries(pg) -> None:
    """The grants as written, exercised against a NON-superuser ingest role.

    Production ingest currently connects as a superuser and bypasses all of
    this; the point of the test is that the grants are correct now, so the
    boundary begins holding the moment that changes.
    """
    with psycopg.connect(pg["admin"], autocommit=True) as conn, conn.cursor() as cur:
        uuid_ = _product(cur, "acme control")
        cur.execute(
            "INSERT INTO catalog.capability_assertion_operator "
            "(product_uuid, capability, polarity, confirmed_by) "
            "VALUES (%s,'rmm',TRUE,'curator')", (uuid_,),
        )

    with psycopg.connect(pg["role_dsn"]("ninja_ingest"), autocommit=True) as conn:
        with conn.cursor() as cur:
            cur.execute(
                "INSERT INTO catalog.capability_assertion_machine "
                "(product_uuid, capability, source_key, confidence, evidence_kind, "
                " matcher_version) VALUES (%s,'rmm','vetted_rule',0.9,'x','t')",
                (uuid_,),
            )
        forbidden = [
            "UPDATE catalog.capability_assertion_operator SET polarity = FALSE",
            "INSERT INTO catalog.capability_assertion_operator "
            "(product_uuid, capability, polarity, confirmed_by) "
            "SELECT product_uuid,'rmm',FALSE,'x' FROM catalog.products",
            "UPDATE catalog.capability_source SET may_alert = FALSE "
            "WHERE source_key = 'lolrmm'",
            "INSERT INTO catalog.capability_rule "
            "(rule_key, capability, title_pattern, source_key) "
            "VALUES ('x','rmm','y','vetted_rule')",
            "DELETE FROM catalog.capability_assertion_machine",
            # Immutable machine columns.
            "UPDATE catalog.capability_assertion_machine SET capability = 'rmm'",
            "UPDATE catalog.capability_assertion_machine SET source_key = 'lolrmm'",
        ]
        for sql in forbidden:
            with conn.cursor() as cur, pytest.raises(psycopg.errors.InsufficientPrivilege):
                cur.execute(sql)


def test_registry_is_read_only_to_runtime_roles(pg) -> None:
    for role in ("operations_app", "ninja_ingest"):
        with psycopg.connect(pg["role_dsn"](role), autocommit=True) as conn:
            with conn.cursor() as cur:
                cur.execute("SELECT count(*) FROM catalog.capability_source")
                assert cur.fetchone()[0] == 5
            with conn.cursor() as cur, pytest.raises(psycopg.errors.InsufficientPrivilege):
                cur.execute(
                    "UPDATE catalog.capability_source SET enabled = FALSE"
                )


def test_effective_view_is_readable_by_every_runtime_role(pg) -> None:
    for role in ("operations_app", "operations_readonly", "metabase_ro", "ninja_ingest"):
        with psycopg.connect(pg["role_dsn"](role), autocommit=True) as conn, conn.cursor() as cur:
            cur.execute("SELECT count(*) FROM catalog.v_product_capability_effective")
            assert cur.fetchone()[0] >= 0


def test_migration_text_has_no_unresolved_placeholder() -> None:
    """Cheap guard: a stray %s in a migration becomes a runtime error only when
    the runner interpolates it."""
    assert not re.search(r"%\(", _MIGRATION.read_text(encoding="utf-8"))
