-- =============================================================================
-- 074_software_catalog_entities.sql
-- Global software reference entities: publisher -> product -> version.
--
-- ADR-0012 section 5, as amended 2026-08-10. Software is not owned: a client
-- owns a license, not Microsoft Word. `operations.entities` is the store for
-- owned things and every structure on it assumes ownership -- NOT NULL tenant,
-- scope_kind, forced RLS with a tenant policy, and 29 composite foreign keys
-- carrying a tenant. Software does not belong there, so it lives here with the
-- other globally-true reference data.
--
-- A separate schema from `intel` on purpose: ADR-0008 defines `intel` as
-- external vulnerability and OSINT *feeds*. These rows are not a feed. They
-- are the canonical catalog those feeds bind to, derived from what we
-- observe across the fleet and normalized through operator-maintained aliases.
--
-- No tenant column, no RLS, no scope_kind -- deliberately, and that is the
-- whole point of the placement. Nothing here is owned by anybody.
--
-- Measured 2026-08-07 against 484,636 installations: 4,863 raw publishers
-- (4,608 after alias normalization), 20,876 products, 40,261 product+version
-- pairs. At the measured 417 bytes/row that is roughly 27 MB.
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS catalog;

GRANT USAGE ON SCHEMA catalog TO operations_app, operations_readonly, metabase_ro, ninja_ingest;

-- Publisher: the vendor, after alias normalization. `publisher_aliases`
-- (operations, operator-maintained) maps raw installation strings onto these
-- names; measured coverage is 84% of installs but only 6% of distinct raw
-- publishers, so the long tail arrives unnormalized and collapses later as
-- aliases are added. That is why `canonical_name` is the key and the raw
-- string stays on the installation row.
CREATE TABLE IF NOT EXISTS catalog.publishers (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canonical_name  text        NOT NULL,
    first_seen_at   timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_catalog_publishers_name UNIQUE (canonical_name)
);

-- Product: a title. Publisher is nullable because 4 of 484,636 installations
-- carry no publisher and a title with an unknown vendor is still a real
-- product -- refusing it would drop observed data to satisfy a shape.
CREATE TABLE IF NOT EXISTS catalog.products (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publisher_id    bigint      REFERENCES catalog.publishers(id) ON DELETE RESTRICT,
    canonical_name  text        NOT NULL,
    first_seen_at   timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_catalog_products_publisher_name UNIQUE (publisher_id, canonical_name)
);

-- Software version: the entity CVEs, EOL dates and safety scores bind to
-- (ADR-0012 s5). `version` is empty rather than NULL when a source reports
-- none -- 13,817 installations (2.9%) have no version, and an empty string
-- keeps the unique constraint usable where NULL would make every unversioned
-- row distinct from every other.
CREATE TABLE IF NOT EXISTS catalog.software_versions (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id      bigint      NOT NULL REFERENCES catalog.products(id) ON DELETE RESTRICT,
    version         text        NOT NULL DEFAULT '',
    eol_date        date,
    eol_source      text        NOT NULL DEFAULT '',
    first_seen_at   timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_catalog_versions_product_version UNIQUE (product_id, version)
);

CREATE INDEX IF NOT EXISTS catalog_products_name_idx
    ON catalog.products (lower(canonical_name));
CREATE INDEX IF NOT EXISTS catalog_versions_product_idx
    ON catalog.software_versions (product_id);
CREATE INDEX IF NOT EXISTS catalog_versions_eol_idx
    ON catalog.software_versions (eol_date) WHERE eol_date IS NOT NULL;

-- Least privilege: the projector runs in ingest and is the sole writer.
-- Operations and Metabase read. Nobody deletes -- a catalog entry that
-- stops being installed is still a real product, and removing it would break
-- every historical installation that pointed at it.
GRANT SELECT ON ALL TABLES IN SCHEMA catalog
    TO operations_app, operations_readonly, metabase_ro;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA catalog TO ninja_ingest;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA catalog TO ninja_ingest;

REVOKE DELETE, TRUNCATE ON ALL TABLES IN SCHEMA catalog
    FROM operations_app, operations_readonly, metabase_ro, ninja_ingest;

ALTER DEFAULT PRIVILEGES IN SCHEMA catalog
    GRANT SELECT ON TABLES TO operations_app, operations_readonly, metabase_ro;

-- The installation relationship already exists -- 484,636 rows carrying
-- install_location and install_date, which is what ADR-0012 s1 requires of a
-- relationship. It does not need rebuilding as a generic relationship; its
-- title strings need an identity to point at. Nullable and unpopulated here:
-- the projector fills it, and until then every existing reader is unaffected.
ALTER TABLE operations.software_installations_current
    ADD COLUMN IF NOT EXISTS software_version_id bigint
    REFERENCES catalog.software_versions(id) ON DELETE RESTRICT;

CREATE INDEX IF NOT EXISTS software_installations_version_idx
    ON operations.software_installations_current (software_version_id)
    WHERE software_version_id IS NOT NULL;
