-- 095: policy platform -> product capability identities.
--
-- A required platform is not a product-name substring. One platform commonly
-- installs an agent, tray process, updater, and uninstall component, all with
-- different product identities. This table is the deliberate many-to-many
-- bridge used by software policy enforcement.
--
-- It lives in operations because it is operator-maintained policy reference
-- data. The raw migration runner owns the DDL because the ingest classifier is
-- its consumer; Operations declares matching state only in migration 0138.

CREATE TABLE IF NOT EXISTS operations.platform_product_map (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id       smallint NOT NULL REFERENCES operations.agents(id) ON DELETE RESTRICT,
    product_uuid   uuid NOT NULL REFERENCES catalog.products(product_uuid) ON DELETE RESTRICT,
    capability     text NOT NULL REFERENCES catalog.capability(key) ON DELETE RESTRICT,
    component_role text NOT NULL DEFAULT 'agent',
    provenance     text NOT NULL DEFAULT '',
    enabled        boolean NOT NULL DEFAULT TRUE,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_platform_product_map_component_role CHECK (
        component_role IN ('agent', 'tray', 'updater', 'uninstaller', 'component')
    ),
    CONSTRAINT ck_platform_product_map_provenance CHECK (provenance <> ''),
    CONSTRAINT uq_platform_product_map_identity UNIQUE (agent_id, product_uuid, capability)
);

CREATE INDEX IF NOT EXISTS idx_platform_product_map_agent_capability
    ON operations.platform_product_map (agent_id, capability)
    WHERE enabled;

-- Operations maintains mappings; ingest only reads them. Explicit grants keep
-- the intended boundary in place once ingest leaves its current superuser role.
REVOKE ALL ON operations.platform_product_map FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE ON operations.platform_product_map TO operations_app;
GRANT SELECT ON operations.platform_product_map
    TO operations_readonly, metabase_ro, ninja_ingest;
REVOKE DELETE, TRUNCATE ON operations.platform_product_map
    FROM operations_app, operations_readonly, metabase_ro, ninja_ingest;
GRANT USAGE, SELECT ON SEQUENCE operations.platform_product_map_id_seq TO operations_app;

COMMENT ON TABLE operations.platform_product_map IS
    'Operator-maintained identity map from a required platform to all catalog products it installs. Replaces substring sanctioning.';
