-- 099: authorization, separated from coverage requirement.
--
-- Until now the classifier derived permission from `required_platforms`: a
-- product was permitted only when the client REQUIRED its platform. The same
-- rows drive `missing_required_platform`, so the only way to authorize
-- software was to mandate it.
--
-- Measured 2026-08-13: ScreenConnect is required by exactly one requirement
-- profile, the global fallback requires only LogMeIn / Ninja / SentinelOne,
-- and 70 of 76 clients have no profile at all -- so the MSP's own ScreenConnect
-- instance on 3,007 devices across 70 clients read as unauthorized. Making it
-- required to silence that would have demanded it from the five clients that
-- do not run it.
--
-- Required stays strictly coverage. Permitted is strictly authorization, and
-- lives here. This table is keyed on the product rather than on a platform,
-- because authorization is a property of the product; `platform_product_map`
-- is untouched and keeps its single job of platform -> product identity.

CREATE TABLE IF NOT EXISTS operations.product_authorizations (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        bigint NOT NULL REFERENCES operations.tenants(id) ON DELETE RESTRICT,
    -- NULL client_id is the global tier: every client of this tenant.
    client_id        uuid NULL REFERENCES operations.clients(id) ON DELETE RESTRICT,
    product_uuid     uuid NOT NULL REFERENCES catalog.products(product_uuid) ON DELETE RESTRICT,
    capability       text NOT NULL REFERENCES catalog.capability(key) ON DELETE RESTRICT,
    -- No default. Permit and deny are opposite decisions and an authorization
    -- must state which one it is; a default would let an incomplete write
    -- silently become a permit.
    polarity         boolean NOT NULL,
    rationale        text NOT NULL,
    authorized_by_id bigint NOT NULL REFERENCES operations.users(id) ON DELETE RESTRICT,
    authorized_at    timestamptz NOT NULL DEFAULT now(),
    -- Nothing leaves this table without a time and a cause.
    withdrawn_at     timestamptz NULL,
    withdrawn_reason text NOT NULL DEFAULT '',
    CONSTRAINT ck_product_authorizations_rationale CHECK (rationale <> ''),
    CONSTRAINT ck_product_authorizations_withdrawal CHECK (
        (withdrawn_at IS NULL AND withdrawn_reason = '')
        OR (withdrawn_at IS NOT NULL AND withdrawn_reason <> '')
    )
);

-- One live authorization per scope. Withdrawn rows are excluded, so
-- re-authorizing inserts a fresh row and the gap stays visible in history
-- rather than being overwritten.
CREATE UNIQUE INDEX IF NOT EXISTS uq_product_authorizations_client_scope
    ON operations.product_authorizations (tenant_id, client_id, product_uuid, capability)
    WHERE withdrawn_at IS NULL AND client_id IS NOT NULL;

-- NULL is not distinct from NULL in a unique index only from PostgreSQL 15
-- with NULLS NOT DISTINCT, so the global tier gets its own partial index
-- rather than relying on that behavior.
CREATE UNIQUE INDEX IF NOT EXISTS uq_product_authorizations_global_scope
    ON operations.product_authorizations (tenant_id, product_uuid, capability)
    WHERE withdrawn_at IS NULL AND client_id IS NULL;

-- The classifier loads every live row for a tenant on each run.
CREATE INDEX IF NOT EXISTS idx_product_authorizations_live
    ON operations.product_authorizations (tenant_id, capability, product_uuid)
    WHERE withdrawn_at IS NULL;

-- Operations authorizes; ingest only reads. DELETE is revoked from both:
-- withdrawal is the retirement path, so an authorization that was once in
-- force can always be shown to have been.
REVOKE ALL ON operations.product_authorizations FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE ON operations.product_authorizations TO operations_app;
GRANT SELECT ON operations.product_authorizations
    TO operations_readonly, metabase_ro, ninja_ingest;
REVOKE DELETE, TRUNCATE ON operations.product_authorizations
    FROM operations_app, operations_readonly, metabase_ro, ninja_ingest;
GRANT USAGE, SELECT ON SEQUENCE operations.product_authorizations_id_seq TO operations_app;

COMMENT ON TABLE operations.product_authorizations IS
    'Operator-maintained authorization: whether a product may carry a capability at a client. Global tier is client_id IS NULL. Strictly separate from coverage requirements, which state what a client must run.';
COMMENT ON COLUMN operations.product_authorizations.polarity IS
    'TRUE permits, FALSE denies. Deliberately has no default: an authorization must state which decision it is.';
