-- 102: data-backed identity values that must never drive a match.
--
-- Explicit filler values are operational data, not Python literals.  The
-- resolver and ingest fast path both read this registry; structural checks
-- (empty, short, or a single repeated character) remain code because they do
-- not enumerate operator-maintained values.

CREATE TABLE IF NOT EXISTS operations.identity_value_rejections (
    id               smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value_kind       text NOT NULL,
    normalized_value text NOT NULL,
    reason           text NOT NULL,
    enabled          boolean NOT NULL DEFAULT TRUE,
    provenance       text NOT NULL DEFAULT 'operations_admin',
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_identity_value_rejections_kind CHECK (value_kind IN ('serial')),
    CONSTRAINT ck_identity_value_rejections_normalized CHECK (
        normalized_value = lower(btrim(normalized_value))
        AND normalized_value <> ''
    ),
    CONSTRAINT ck_identity_value_rejections_reason CHECK (reason <> ''),
    CONSTRAINT ck_identity_value_rejections_provenance CHECK (provenance <> ''),
    CONSTRAINT uq_identity_value_rejections_value UNIQUE (value_kind, normalized_value)
);

INSERT INTO operations.identity_value_rejections
    (value_kind, normalized_value, reason, provenance)
VALUES
    ('serial', 'none', 'Firmware placeholder serial', 'migration_102'),
    ('serial', 'null', 'Firmware placeholder serial', 'migration_102'),
    ('serial', 'default string', 'Firmware placeholder serial', 'migration_102'),
    ('serial', 'to be filled by o.e.m.', 'Firmware placeholder serial', 'migration_102'),
    ('serial', 'to be filled by o.e.m', 'Firmware placeholder serial', 'migration_102'),
    ('serial', 'system serial number', 'Firmware placeholder serial', 'migration_102'),
    ('serial', 'chassis serial number', 'Firmware placeholder serial', 'migration_102'),
    ('serial', '123-1234-123', 'Firmware placeholder serial', 'migration_102'),
    ('serial', 'invalid', 'Firmware placeholder serial', 'migration_102'),
    ('serial', 'not specified', 'Firmware placeholder serial', 'migration_102'),
    ('serial', 'not applicable', 'Firmware placeholder serial', 'migration_102'),
    ('serial', 'n/a', 'Firmware placeholder serial', 'migration_102'),
    ('serial', 'na', 'Firmware placeholder serial', 'migration_102'),
    ('serial', 'unknown', 'Firmware placeholder serial', 'migration_102'),
    ('serial', '0', 'Firmware placeholder serial', 'migration_102'),
    ('serial', '00000000', 'Firmware placeholder serial', 'migration_102'),
    ('serial', '0123456789', 'Firmware placeholder serial', 'migration_102')
ON CONFLICT (value_kind, normalized_value) DO NOTHING;

REVOKE ALL ON operations.identity_value_rejections FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE ON operations.identity_value_rejections TO operations_app;
GRANT SELECT ON operations.identity_value_rejections
    TO operations_readonly, metabase_ro, ninja_ingest;
REVOKE DELETE, TRUNCATE ON operations.identity_value_rejections
    FROM operations_app, operations_readonly, metabase_ro, ninja_ingest;
GRANT USAGE, SELECT ON SEQUENCE operations.identity_value_rejections_id_seq
    TO operations_app;

COMMENT ON TABLE operations.identity_value_rejections IS
    'Operator-maintained normalized identity values rejected from matching. Structural quality rules remain in ingest code.';
