-- 106: wire the already-seeded but unused winget_tag/chocolatey_tag rows in
-- catalog.capability_source (093) into the capability model as real,
-- non-alerting candidate evidence.
--
-- 093 seeded these two source_key rows (authority_class='community_tag',
-- may_alert=FALSE) but nothing ever wrote catalog.capability_assertion_machine
-- with them: catalog.capability_rule's own ck_capability_rule_source CHECK
-- restricts that table to ('vetted_rule', 'publisher_rule') by design (a rule
-- there is a title/publisher pattern, not a tag), so tag-based evidence needs
-- its own rule table -- this is that table, mirroring catalog.category_tag_rule
-- (104) exactly, on the capability axis instead of the category axis.
--
-- 104's own comment names the reason these two axes stay separate: anydesk,
-- teamviewer and chrome remote desktop already carry real tags ("rdp",
-- "remote-control", "remote-desktop") that migration 104 deliberately did NOT
-- map into software_category, because doing so would assert a second,
-- competing "remote access" truth outside catalog.capability for products it
-- already covers. This table is where that vocabulary belongs instead.
--
-- Seeded from the real tag vocabulary measured 2026-08-19 across the same 47
-- exact matches 104 was seeded from. Only remote_access has evidence-backed
-- tags in that sample; endpoint_security and rmm get no seed rows here until a
-- real exact match produces one -- an empty capability for now, not a guess.
-- Generic tags seen in the same sample ("remote", "control", "admin",
-- "support", "viewer", "desktop") are deliberately NOT mapped: they are too
-- loose to anchor a capability, the same anchoring discipline capability_rule
-- itself enforces structurally (ck_capability_rule_anchored) for patterns.

CREATE TABLE IF NOT EXISTS catalog.capability_tag_rule (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag        text NOT NULL,
    capability text NOT NULL REFERENCES catalog.capability (key),
    enabled    boolean NOT NULL DEFAULT TRUE,
    notes      text NOT NULL DEFAULT '',
    CONSTRAINT ck_capability_tag_rule_tag_lower CHECK (tag = LOWER(tag)),
    UNIQUE (tag, capability)
);

CREATE INDEX IF NOT EXISTS idx_capability_tag_rule_tag
    ON catalog.capability_tag_rule (tag) WHERE enabled;

INSERT INTO catalog.capability_tag_rule (tag, capability, notes) VALUES
    ('rdp',             'remote_access', ''),
    ('remote-control',  'remote_access', ''),
    ('remote-desktop',  'remote_access', ''),
    ('remote-access',   'remote_access', ''),
    ('chromoting',      'remote_access',
     'Chrome Remote Desktop''s own protocol name, unambiguous on its own.')
ON CONFLICT (tag, capability) DO NOTHING;

-- Migration-managed only, same as capability_rule and category_tag_rule: no
-- runtime writer for vocabulary.
REVOKE ALL ON catalog.capability_tag_rule FROM PUBLIC;

REVOKE INSERT, UPDATE, DELETE, TRUNCATE
    ON catalog.capability_tag_rule
  FROM operations_app, ninja_ingest;

GRANT SELECT ON catalog.capability_tag_rule
   TO operations_app, operations_readonly, metabase_ro, ninja_ingest;

GRANT USAGE, SELECT ON SEQUENCE
    catalog.capability_tag_rule_id_seq TO ninja_ingest;

COMMENT ON TABLE catalog.capability_tag_rule IS
    'Tag -> capability, for winget_tag/chocolatey_tag evidence only. '
    'capability_rule cannot carry these source_keys by its own CHECK '
    'constraint, because a rule there is a title/publisher pattern, not a '
    'tag.';
