# Generated by Django 5.1.15 on 2026-07-06 18:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('kind', models.CharField(max_length=80)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'sources',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=120)),
                ('display_name', models.CharField(max_length=240)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.tenant')),
            ],
            options={
                'db_table': 'clients',
                'ordering': ('display_name',),
            },
        ),
        migrations.CreateModel(
            name='ClientPolicy',
            fields=[
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=80)),
                ('approved_products', models.JSONField(blank=True, default=list)),
                ('agent_sla_days', models.PositiveIntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='operations.client')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.tenant')),
            ],
            options={
                'db_table': 'client_policies',
            },
        ),
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_email', models.EmailField(blank=True, max_length=254)),
                ('canonical_username', models.CharField(blank=True, max_length=255)),
                ('display_name', models.CharField(max_length=240)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_users', to='operations.client')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.tenant')),
            ],
            options={
                'db_table': 'client_users',
                'ordering': ('display_name',),
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_hostname', models.CharField(max_length=255)),
                ('canonical_serial', models.CharField(blank=True, max_length=255)),
                ('canonical_vm_uuid', models.CharField(blank=True, max_length=64)),
                ('device_kind', models.CharField(choices=[('physical', 'Physical'), ('vm-with-agent', 'VM with agent'), ('vm-agentless', 'VM agentless'), ('hypervisor-host', 'Hypervisor host'), ('network-device', 'Network device'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='operations.client')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.tenant')),
            ],
            options={
                'db_table': 'devices',
                'ordering': ('canonical_hostname',),
            },
        ),
        migrations.CreateModel(
            name='DeviceLink',
            fields=[
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=240)),
                ('external_name', models.CharField(blank=True, max_length=240)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='operations.device')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.tenant')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_links', to='operations.source')),
            ],
            options={
                'db_table': 'device_links',
            },
        ),
        migrations.CreateModel(
            name='ClientUserLink',
            fields=[
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=240)),
                ('external_name', models.CharField(blank=True, max_length=240)),
                ('client_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='operations.clientuser')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.tenant')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_user_links', to='operations.source')),
            ],
            options={
                'db_table': 'client_user_links',
            },
        ),
        migrations.CreateModel(
            name='ClientLink',
            fields=[
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=240)),
                ('external_name', models.CharField(blank=True, max_length=240)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='operations.client')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.tenant')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_links', to='operations.source')),
            ],
            options={
                'db_table': 'client_links',
            },
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='uq_clients_tenant_slug'),
        ),
        migrations.AddConstraint(
            model_name='clientpolicy',
            constraint=models.UniqueConstraint(fields=('tenant', 'client', 'category'), name='uq_client_policies_tenant_client_category'),
        ),
        migrations.AddConstraint(
            model_name='devicelink',
            constraint=models.UniqueConstraint(fields=('tenant', 'source', 'external_id'), name='uq_device_links_tenant_source_external_id'),
        ),
        migrations.AddConstraint(
            model_name='clientuserlink',
            constraint=models.UniqueConstraint(fields=('tenant', 'source', 'external_id'), name='uq_client_user_links_tenant_source_external_id'),
        ),
        migrations.AddConstraint(
            model_name='clientlink',
            constraint=models.UniqueConstraint(fields=('tenant', 'source', 'external_id'), name='uq_client_links_tenant_source_external_id'),
        ),
    ]
