# Generated by Django 5.1.15 on 2026-07-06 18:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_source_client_clientpolicy_clientuser_device_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('kind', models.CharField(max_length=80)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'collectors',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FindingType',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('default_severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('runbook_path', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'finding_types',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CollectorInstance',
            fields=[
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(max_length=80)),
                ('token_hash', models.CharField(blank=True, max_length=255)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.tenant')),
            ],
            options={
                'db_table': 'collector_instances',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SourceInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_instances', to='operations.client')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='operations.source')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.tenant')),
            ],
            options={
                'db_table': 'source_instances',
            },
        ),
        migrations.CreateModel(
            name='SourceBinding',
            fields=[
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schedule', models.CharField(blank=True, max_length=120)),
                ('enabled', models.BooleanField(default=True)),
                ('collector_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_bindings', to='operations.collectorinstance')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.tenant')),
                ('source_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='operations.sourceinstance')),
            ],
            options={
                'db_table': 'source_bindings',
            },
        ),
        migrations.AddConstraint(
            model_name='collectorinstance',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uq_collector_instances_tenant_name'),
        ),
        migrations.AddConstraint(
            model_name='sourcebinding',
            constraint=models.UniqueConstraint(fields=('tenant', 'source_instance', 'collector_instance'), name='uq_source_bindings_tenant_source_collector'),
        ),
    ]
