# Generated by Django 5.1.15 on 2026-07-06 18:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def create_software_installations_current(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(
        """
        CREATE TABLE IF NOT EXISTS operations.software_installations_current (
            tenant_id bigint NOT NULL REFERENCES operations.tenants(id),
            client_id uuid NOT NULL REFERENCES operations.clients(id),
            device_id uuid NOT NULL REFERENCES operations.devices(id),
            canonical_name text NOT NULL,
            publisher text,
            version text,
            install_location text,
            install_date date,
            first_observed_at timestamptz NOT NULL,
            last_observed_at timestamptz NOT NULL,
            refreshed_at timestamptz NOT NULL,
            PRIMARY KEY (tenant_id, client_id, device_id, canonical_name)
        )
        """
    )
    schema_editor.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_sw_install_current_client_product
        ON operations.software_installations_current
            (tenant_id, client_id, canonical_name)
        """
    )
    schema_editor.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_sw_install_current_device_product
        ON operations.software_installations_current
            (tenant_id, device_id, canonical_name)
        """
    )
    schema_editor.execute(
        """
        CREATE OR REPLACE FUNCTION operations.refresh_software_installations_current(
            p_tenant_id bigint DEFAULT NULL
        ) RETURNS void
        LANGUAGE plpgsql
        SECURITY DEFINER
        SET search_path = operations, pg_temp
        AS $$
        BEGIN
            WITH latest AS (
                SELECT DISTINCT ON
                    (tenant_id, client_id, device_id, entity_key)
                    tenant_id,
                    client_id,
                    device_id,
                    entity_key AS canonical_name,
                    raw_data ->> 'publisher' AS publisher,
                    raw_data ->> 'version' AS version,
                    raw_data ->> 'location' AS install_location,
                    NULLIF(raw_data ->> 'installDate', '')::date AS install_date,
                    MIN(observed_at) OVER (
                        PARTITION BY tenant_id, client_id, device_id, entity_key
                    ) AS first_observed_at,
                    observed_at AS last_observed_at
                FROM operations.entity_observations
                WHERE entity_type = 'software'
                  AND client_id IS NOT NULL
                  AND device_id IS NOT NULL
                  AND (p_tenant_id IS NULL OR tenant_id = p_tenant_id)
                ORDER BY tenant_id, client_id, device_id, entity_key,
                         observed_at DESC
            )
            INSERT INTO operations.software_installations_current AS t
                (tenant_id, client_id, device_id, canonical_name,
                 publisher, version, install_location, install_date,
                 first_observed_at, last_observed_at, refreshed_at)
            SELECT tenant_id, client_id, device_id, canonical_name,
                   publisher, version, install_location, install_date,
                   first_observed_at, last_observed_at, now()
              FROM latest
            ON CONFLICT (tenant_id, client_id, device_id, canonical_name)
            DO UPDATE SET
                publisher = EXCLUDED.publisher,
                version = EXCLUDED.version,
                install_location = EXCLUDED.install_location,
                install_date = EXCLUDED.install_date,
                first_observed_at = LEAST(
                    t.first_observed_at,
                    EXCLUDED.first_observed_at
                ),
                last_observed_at = GREATEST(
                    t.last_observed_at,
                    EXCLUDED.last_observed_at
                ),
                refreshed_at = now();

            DELETE FROM operations.software_installations_current t
            WHERE (p_tenant_id IS NULL OR t.tenant_id = p_tenant_id)
              AND NOT EXISTS (
                  SELECT 1
                    FROM operations.entity_observations o
                   WHERE o.entity_type = 'software'
                     AND o.tenant_id = t.tenant_id
                     AND o.client_id = t.client_id
                     AND o.device_id = t.device_id
                     AND o.entity_key = t.canonical_name
              );
        END;
        $$;
        """
    )


def drop_software_installations_current(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(
        "DROP FUNCTION IF EXISTS operations.refresh_software_installations_current(bigint)"
    )
    schema_editor.execute("DROP TABLE IF EXISTS operations.software_installations_current")


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_collector_findingtype_collectorinstance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadLetterObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('envelope', models.JSONField(default=dict)),
                ('reject_reason', models.TextField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('collector_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dead_letter_observations', to='operations.collectorinstance')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_dead_letters', to=settings.AUTH_USER_MODEL)),
                ('source_binding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dead_letter_observations', to='operations.sourcebinding')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.tenant')),
            ],
            options={
                'db_table': 'dead_letter_observations',
                'indexes': [models.Index(fields=['tenant', 'received_at'], name='idx_dead_letter_received_at'), models.Index(fields=['tenant', 'resolved_at'], name='idx_dead_letter_resolved_at')],
            },
        ),
        migrations.CreateModel(
            name='EntityObservation',
            fields=[
                ('observation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=80)),
                ('entity_key', models.TextField()),
                ('platform', models.CharField(max_length=80)),
                ('subplatform', models.CharField(blank=True, max_length=120)),
                ('observed_at', models.DateTimeField()),
                ('raw_data', models.JSONField(default=dict)),
                ('canonical_data', models.JSONField(default=dict)),
                ('batch_id', models.UUIDField()),
                ('observation_hash', models.BinaryField()),
                ('collector_version', models.CharField(blank=True, max_length=80)),
                ('schema_version', models.PositiveIntegerField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='operations.client')),
                ('collector_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entity_observations', to='operations.collectorinstance')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='operations.device')),
                ('source_binding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entity_observations', to='operations.sourcebinding')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.tenant')),
            ],
            options={
                'db_table': 'entity_observations',
                'indexes': [models.Index(fields=['tenant', 'entity_type', 'entity_key'], name='idx_entity_obs_entity_key'), models.Index(fields=['tenant', 'client', 'device'], name='idx_entity_obs_client_device'), models.Index(fields=['tenant', 'observed_at'], name='idx_entity_obs_observed_at')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'collector_instance', 'batch_id', 'observation_hash'), name='uq_entity_obs_tenant_collector_batch_hash')],
            },
        ),
        migrations.RunPython(
            create_software_installations_current,
            drop_software_installations_current,
        ),
    ]
