# Generated by Django 5.1.15 on 2026-07-06 19:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_deadletterobservation_entityobservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity_min', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], max_length=16)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('slack', 'Slack'), ('teams', 'Teams'), ('webhook', 'Webhook')], max_length=16)),
                ('target', models.TextField()),
                ('mode', models.CharField(choices=[('immediate', 'Immediate'), ('digest', 'Digest')], max_length=16)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notification_routes', to='operations.client')),
                ('finding_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notification_routes', to='operations.findingtype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.tenant')),
            ],
            options={
                'db_table': 'notification_routes',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('audit_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_kind', models.CharField(choices=[('user', 'User'), ('collector', 'Collector'), ('system', 'System')], max_length=16)),
                ('source', models.CharField(choices=[('ui', 'UI'), ('api', 'API'), ('ingest', 'Ingest'), ('management_command', 'Management command'), ('background_job', 'Background job'), ('celery', 'Celery')], max_length=32)),
                ('action', models.CharField(max_length=120)),
                ('entity_type', models.CharField(max_length=80)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('before_state', models.JSONField(blank=True, null=True)),
                ('after_state', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.tenant')),
            ],
            options={
                'db_table': 'audit_log',
                'indexes': [models.Index(fields=['tenant', 'occurred_at'], name='idx_audit_log_occurred_at'), models.Index(fields=['tenant', 'entity_type', 'entity_id'], name='idx_audit_log_entity')],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_type', models.CharField(choices=[('client', 'Client'), ('device', 'Device'), ('client_user', 'Client user'), ('source_binding', 'Source binding'), ('collector_instance', 'Collector instance')], max_length=32)),
                ('subject_id', models.UUIDField()),
                ('finding_details', models.JSONField(blank=True, default=dict)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], default='medium', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('investigating', 'Investigating'), ('suppressed', 'Suppressed'), ('resolved', 'Resolved'), ('wontfix', "Won't fix")], default='open', max_length=24)),
                ('sla_due_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('finding_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='operations.findingtype')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_findings', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.tenant')),
            ],
            options={
                'db_table': 'findings',
                'indexes': [models.Index(fields=['tenant', 'status', 'severity'], name='idx_findings_status_severity'), models.Index(fields=['tenant', 'subject_type', 'subject_id'], name='idx_findings_subject')],
            },
        ),
        migrations.CreateModel(
            name='MergeCandidate',
            fields=[
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=80)),
                ('canonical_key', models.TextField()),
                ('member_snapshots', models.JSONField(default=list)),
                ('member_observation_ids', models.JSONField(blank=True, null=True)),
                ('match_reason', models.TextField(blank=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('merged', 'Merged'), ('split', 'Split'), ('rejected', 'Rejected')], default='open', max_length=16)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merge_candidates', to='operations.client')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.tenant')),
            ],
            options={
                'db_table': 'merge_candidates',
                'indexes': [models.Index(fields=['tenant', 'client', 'entity_type', 'status'], name='idx_merge_candidates_scope')],
            },
        ),
        migrations.CreateModel(
            name='RunLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=80)),
                ('subject_ref', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('ok', models.BooleanField(default=False)),
                ('rows', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.tenant')),
            ],
            options={
                'db_table': 'run_log',
                'indexes': [models.Index(fields=['tenant', 'kind', 'started_at'], name='idx_run_log_kind_started')],
            },
        ),
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('encrypted_value', models.BinaryField()),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_secrets', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.tenant')),
            ],
            options={
                'db_table': 'secrets',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name'), name='uq_secrets_tenant_name')],
            },
        ),
        migrations.CreateModel(
            name='SoftwareCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_name', models.CharField(max_length=255)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('publisher_hint', models.CharField(blank=True, max_length=255)),
                ('eol_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operations.tenant')),
            ],
            options={
                'db_table': 'software_catalog',
                'ordering': ('canonical_name',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('tenant__isnull', True)), fields=('canonical_name',), name='software_catalog_global_unique'), models.UniqueConstraint(condition=models.Q(('tenant__isnull', False)), fields=('tenant', 'canonical_name'), name='software_catalog_tenant_unique')],
            },
        ),
        migrations.CreateModel(
            name='SoftwareDecision',
            fields=[
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_name', models.CharField(max_length=255)),
                ('decision', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('investigate', 'Investigate'), ('approve_publisher', 'Approve publisher')], max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='software_decisions', to='operations.client')),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='software_decisions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.tenant')),
            ],
            options={
                'db_table': 'software_decisions',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'client', 'canonical_name'), name='uq_software_decisions_tenant_client_name')],
            },
        ),
        migrations.CreateModel(
            name='SuppressionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_match', models.JSONField(default=dict)),
                ('reason', models.TextField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suppression_rules', to=settings.AUTH_USER_MODEL)),
                ('finding_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suppression_rules', to='operations.findingtype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.tenant')),
            ],
            options={
                'db_table': 'suppression_rules',
                'indexes': [models.Index(fields=['tenant', 'finding_type'], name='idx_suppression_rules_type')],
            },
        ),
    ]
