# Generated by Django 5.1.15 on 2026-07-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_seed_m0_reference_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_kind',
            field=models.CharField(choices=[('physical', 'Physical'), ('vm-with-agent', 'VM with agent'), ('vm-agentless', 'VM agentless'), ('hypervisor-host', 'Hypervisor host'), ('network-device', 'Network device'), ('unknown', 'Unknown')], default='unknown', max_length=32, verbose_name='Type'),
        ),
    ]
