# Generated by Django 5.1.15 on 2026-07-21 22:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0062_grant_ninja_activities_select'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityObservationCurrent',
            fields=[
                ('observation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=80)),
                ('parent_source_key', models.TextField(default='')),
                ('entity_key', models.TextField()),
                ('platform', models.CharField(max_length=80)),
                ('subplatform', models.CharField(blank=True, max_length=120)),
                ('observed_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('last_received_at', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('snapshot_scope', models.CharField(blank=True, max_length=120)),
                ('last_snapshot_run_id', models.UUIDField(blank=True, null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('canonical_data', models.JSONField(default=dict)),
                ('raw_hash', models.BinaryField(blank=True, null=True)),
                ('material_hash', models.BinaryField()),
                ('hash_algorithm_version', models.PositiveIntegerField(default=1)),
                ('batch_id', models.UUIDField()),
                ('collector_version', models.CharField(blank=True, max_length=80)),
                ('schema_version', models.PositiveIntegerField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_observations', to='operations.client')),
                ('collector_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_observations', to='operations.collectorinstance')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_observations', to='operations.device')),
                ('source_binding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_observations', to='operations.sourcebinding')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.tenant')),
            ],
            options={
                'db_table': 'entity_observation_current',
                'indexes': [models.Index(fields=['tenant', 'active', 'entity_type'], name='idx_obs_current_active'), models.Index(fields=['tenant', 'observed_at'], name='idx_obs_current_observed')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'source_binding', 'entity_type', 'parent_source_key', 'entity_key'), name='uq_obs_current_identity')],
            },
        ),
        migrations.CreateModel(
            name='EntityObservationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=80)),
                ('parent_source_key', models.TextField(default='')),
                ('entity_key', models.TextField()),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField()),
                ('received_at', models.DateTimeField()),
                ('material_data', models.JSONField(default=dict)),
                ('material_hash', models.BinaryField()),
                ('hash_algorithm_version', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('collector_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history_observations', to='operations.collectorinstance')),
                ('source_binding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history_observations', to='operations.sourcebinding')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.tenant')),
            ],
            options={
                'db_table': 'entity_observation_history',
                'indexes': [models.Index(fields=['tenant', 'effective_from'], name='idx_obs_hist_effective'), models.Index(fields=['tenant', 'effective_to'], name='idx_obs_hist_retention')],
            },
        ),
    ]
