# Generated by Django 5.1.15 on 2026-07-21 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0063_alter_coveragerequirement_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='entityobservationhistory',
            constraint=models.UniqueConstraint(condition=models.Q(('effective_to__isnull', True)), fields=('tenant', 'source_binding', 'entity_type', 'parent_source_key', 'entity_key'), name='uq_obs_hist_open_identity'),
        ),
    ]
