# Generated by Django 5.1.15 on 2026-07-21 23:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0064_entityobservationhistory_uq_obs_hist_open_identity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coveragerequirement',
            options={'ordering': ('entity_type', 'platform')},
        ),
        migrations.AlterModelOptions(
            name='queueregistry',
            options={'ordering': ('queue_key',)},
        ),
        migrations.CreateModel(
            name='ObservationSnapshotRun',
            fields=[
                ('run_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_scope', models.CharField(max_length=120)),
                ('snapshot_at', models.DateTimeField()),
                ('status', models.CharField(default='started', max_length=20)),
                ('expected_rows', models.PositiveIntegerField(default=0)),
                ('written_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('source_binding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observation_snapshot_runs', to='operations.sourcebinding')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.tenant')),
            ],
            options={
                'db_table': 'observation_snapshot_runs',
                'indexes': [models.Index(fields=['tenant', 'source_binding', 'snapshot_scope', 'snapshot_at'], name='idx_obs_snapshot_latest'), models.Index(fields=['tenant', 'status'], name='idx_obs_snapshot_status')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'source_binding', 'snapshot_scope', 'snapshot_at'), name='uq_obs_snapshot_run_boundary')],
            },
        ),
    ]
