# Generated by Django 5.1.15 on 2026-07-22 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0066_observation_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityobservationhistory',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observation_history', to='operations.device'),
        ),
        migrations.AddField(
            model_name='entityobservationhistory',
            name='platform',
            field=models.CharField(default='', max_length=80),
        ),
    ]
