# Generated by Django 5.1.15 on 2026-07-22 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0071_source_health_current_observations'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityobservationhistory',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observation_history', to='operations.client'),
        ),
    ]
