# Generated by Django 5.1.15 on 2026-07-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0078_software_installations_lower_canonical_idx'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='softwaredecision',
            name='uq_software_decisions_global',
        ),
        migrations.RemoveConstraint(
            model_name='softwaredecision',
            name='uq_software_decisions_client',
        ),
        migrations.RemoveConstraint(
            model_name='softwaredecision',
            name='uq_software_decisions_device',
        ),
        migrations.AddField(
            model_name='softwaredecision',
            name='publisher',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='softwaredecision',
            name='canonical_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='softwaredecision',
            constraint=models.UniqueConstraint(condition=models.Q(('client__isnull', True), ('device__isnull', True), models.Q(('canonical_name', ''), _negated=True)), fields=('tenant', 'canonical_name'), name='uq_software_decisions_global'),
        ),
        migrations.AddConstraint(
            model_name='softwaredecision',
            constraint=models.UniqueConstraint(condition=models.Q(('client__isnull', False), ('device__isnull', True), models.Q(('canonical_name', ''), _negated=True)), fields=('tenant', 'client', 'canonical_name'), name='uq_software_decisions_client'),
        ),
        migrations.AddConstraint(
            model_name='softwaredecision',
            constraint=models.UniqueConstraint(condition=models.Q(('device__isnull', False), models.Q(('canonical_name', ''), _negated=True)), fields=('tenant', 'device', 'canonical_name'), name='uq_software_decisions_device'),
        ),
        migrations.AddConstraint(
            model_name='softwaredecision',
            constraint=models.UniqueConstraint(condition=models.Q(('client__isnull', True), ('device__isnull', True), models.Q(('publisher', ''), _negated=True)), fields=('tenant', 'publisher'), name='uq_software_decisions_pub_global'),
        ),
        migrations.AddConstraint(
            model_name='softwaredecision',
            constraint=models.UniqueConstraint(condition=models.Q(('client__isnull', False), ('device__isnull', True), models.Q(('publisher', ''), _negated=True)), fields=('tenant', 'client', 'publisher'), name='uq_software_decisions_pub_client'),
        ),
        migrations.AddConstraint(
            model_name='softwaredecision',
            constraint=models.UniqueConstraint(condition=models.Q(('device__isnull', False), models.Q(('publisher', ''), _negated=True)), fields=('tenant', 'device', 'publisher'), name='uq_software_decisions_pub_device'),
        ),
        migrations.AddConstraint(
            model_name='softwaredecision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('canonical_name', ''), models.Q(('publisher', ''), _negated=True)), models.Q(models.Q(('canonical_name', ''), _negated=True), ('publisher', '')), _connector='OR'), name='ck_software_decisions_scope_key_xor'),
        ),
    ]
