# Generated by Django 5.1.15 on 2026-07-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0085_findings_subject_layer_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublisherCategory',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('publisher_pattern', models.CharField(help_text='SQL ILIKE pattern; matched against the canonical publisher after PublisherAlias normalization.', max_length=255)),
                ('categories', models.JSONField(blank=True, default=list, help_text="List of category tokens, e.g. ['browser', 'productivity'].")),
                ('is_regex', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, default='', max_length=240)),
                ('priority', models.SmallIntegerField(default=0, help_text='Higher priority wins when multiple patterns match the same publisher. Ties broken by id.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'publisher_categories',
                'ordering': ('-priority', 'publisher_pattern'),
            },
        ),
        migrations.CreateModel(
            name='IntelMatcherHint',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('require_third_token', 'Require third token'), ('ignore_sub_component', 'Ignore sub-component')], max_length=32)),
                ('pattern', models.CharField(help_text="For require_third_token: the vendor token (lowercase, e.g. 'microsoft'). For ignore_sub_component: a Python regex matched case-insensitively against the canonical name.", max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, default='', max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'intel_matcher_hints',
                'ordering': ('kind', 'pattern'),
                'constraints': [models.UniqueConstraint(fields=('kind', 'pattern'), name='uq_intel_matcher_hint_kind_pattern')],
            },
        ),
        migrations.CreateModel(
            name='PublisherAlias',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('raw_pattern', models.CharField(help_text='SQL ILIKE pattern (use %% wildcards) OR exact string. Matched case-insensitively against operations.software_installations_current.publisher.', max_length=255)),
                ('canonical_publisher', models.CharField(max_length=255)),
                ('is_regex', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, default='', max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'publisher_aliases',
                'ordering': ('canonical_publisher', 'raw_pattern'),
                'constraints': [models.UniqueConstraint(fields=('raw_pattern',), name='uq_publisher_alias_raw_pattern')],
            },
        ),
    ]
