# Generated by Django 5.1.15 on 2026-07-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0088_v_software_safety_matview_and_band_rework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishercategory',
            name='categories',
            field=models.JSONField(blank=True, default=list, help_text='List of category tokens from the canonical MSP taxonomy: system, driver, security, av, edr, browser, productivity, communication, media, development, runtime, remote-access, management, rmm, backup, virtualization, storage, networking, database, engineering, utility. Free-form tokens are allowed but the built-in category chip strip only surfaces tokens operators have historically used, so a stable token wins.'),
        ),
    ]
