# Generated by Django 5.1.15 on 2026-08-03 22:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


SEED_ENTITY_CLASSES_SQL = r"""
INSERT INTO operations.entity_classes (name, display_name, description) VALUES
    ('client', 'Client', 'Tenant-owned customer or organizational boundary.'),
    ('device', 'Device', 'Client-owned managed or observed computing/network device.'),
    ('user', 'User', 'Client-owned person or account.'),
    ('peripheral', 'Peripheral', 'Client-owned attached peripheral.'),
    ('asset', 'Asset', 'Client-owned documented or managed asset.'),
    ('software', 'Software', 'Client-owned software product or installation concept.'),
    ('service', 'Service', 'Tenant- or client-scoped managed service.'),
    ('unknown', 'Unknown', 'Unclassified evidence; deny-by-default authority.')
ON CONFLICT (name) DO NOTHING;
"""

FORWARD_SQL = r"""
SET CONSTRAINTS ALL IMMEDIATE;

INSERT INTO operations.entity_classes (name, display_name, description) VALUES
    ('client', 'Client', 'Tenant-owned customer or organizational boundary.'),
    ('device', 'Device', 'Client-owned managed or observed computing/network device.'),
    ('user', 'User', 'Client-owned person or account.'),
    ('peripheral', 'Peripheral', 'Client-owned attached peripheral.'),
    ('asset', 'Asset', 'Client-owned documented or managed asset.'),
    ('software', 'Software', 'Client-owned software product or installation concept.'),
    ('service', 'Service', 'Tenant- or client-scoped managed service.'),
    ('unknown', 'Unknown', 'Unclassified evidence; deny-by-default authority.')
ON CONFLICT (name) DO NOTHING;

INSERT INTO operations.entity_class_scopes (entity_class_id, scope_kind) VALUES
    ('client', 'tenant'),
    ('device', 'client'),
    ('user', 'client'),
    ('peripheral', 'client'),
    ('asset', 'client'),
    ('software', 'client'),
    ('service', 'tenant'),
    ('service', 'client'),
    ('unknown', 'tenant'),
    ('unknown', 'client')
ON CONFLICT (entity_class_id, scope_kind) DO NOTHING;

UPDATE operations.entity_types
   SET entity_class_id = CASE name
       WHEN 'agent.rmm' THEN 'device'
       WHEN 'agent.edr' THEN 'device'
       WHEN 'agent.remote_access' THEN 'device'
       WHEN 'vm.host' THEN 'device'
       WHEN 'vm.guest' THEN 'device'
       WHEN 'network.device' THEN 'device'
       WHEN 'monitor.target' THEN 'device'
       WHEN 'cmdb.asset' THEN 'asset'
       WHEN 'software' THEN 'software'
       WHEN 'org' THEN 'client'
       ELSE 'unknown'
   END,
       consumes_license = FALSE,
       requirement_eligible = name IN (
           'agent.rmm', 'agent.edr', 'agent.remote_access'
       );

ALTER TABLE operations.entities
    ADD CONSTRAINT fk_entities_class_scope
    FOREIGN KEY (entity_class_id, scope_kind)
    REFERENCES operations.entity_class_scopes (entity_class_id, scope_kind)
    ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE operations.clients
    ADD CONSTRAINT uq_clients_tenant_id UNIQUE (tenant_id, id);
ALTER TABLE operations.devices
    ADD CONSTRAINT uq_devices_tenant_id UNIQUE (tenant_id, id);
ALTER TABLE operations.source_instances
    ADD CONSTRAINT uq_source_instances_tenant_id UNIQUE (tenant_id, id);
ALTER TABLE operations.source_bindings
    ADD CONSTRAINT uq_source_bindings_tenant_id UNIQUE (tenant_id, id);

ALTER TABLE operations.entities
    ADD CONSTRAINT fk_entities_tenant_client
    FOREIGN KEY (tenant_id, client_id)
    REFERENCES operations.clients (tenant_id, id)
    ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE operations.clients
    ADD CONSTRAINT fk_clients_tenant_entity
    FOREIGN KEY (tenant_id, entity_id)
    REFERENCES operations.entities (tenant_id, id)
    ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE operations.devices
    ADD CONSTRAINT fk_devices_tenant_entity
    FOREIGN KEY (tenant_id, entity_id)
    REFERENCES operations.entities (tenant_id, id)
    ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE operations.entity_source_links
    ADD CONSTRAINT fk_entity_links_tenant_entity_class
    FOREIGN KEY (tenant_id, entity_id, entity_class_id)
    REFERENCES operations.entities (tenant_id, id, entity_class_id)
    ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_entity_links_tenant_source
    FOREIGN KEY (tenant_id, source_instance_id)
    REFERENCES operations.source_instances (tenant_id, id)
    ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_entity_links_tenant_binding
    FOREIGN KEY (tenant_id, last_seen_binding_id)
    REFERENCES operations.source_bindings (tenant_id, id)
    ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE operations.entity_source_link_history
    ADD CONSTRAINT fk_entity_link_hist_tenant_entity_class
    FOREIGN KEY (tenant_id, entity_id, entity_class_id)
    REFERENCES operations.entities (tenant_id, id, entity_class_id)
    ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_entity_link_hist_tenant_source
    FOREIGN KEY (tenant_id, source_instance_id)
    REFERENCES operations.source_instances (tenant_id, id)
    ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_entity_link_hist_tenant_binding
    FOREIGN KEY (tenant_id, last_seen_binding_id)
    REFERENCES operations.source_bindings (tenant_id, id)
    ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE operations.entity_candidates
    ADD CONSTRAINT fk_entity_candidates_tenant_source
    FOREIGN KEY (tenant_id, source_instance_id)
    REFERENCES operations.source_instances (tenant_id, id)
    ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_entity_candidates_tenant_client
    FOREIGN KEY (tenant_id, client_id)
    REFERENCES operations.clients (tenant_id, id)
    ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_entity_candidates_tenant_proposed
    FOREIGN KEY (tenant_id, proposed_entity_id, proposed_entity_class_id)
    REFERENCES operations.entities (tenant_id, id, entity_class_id)
    ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_entity_candidates_tenant_resolved
    FOREIGN KEY (tenant_id, resolved_entity_id, proposed_entity_class_id)
    REFERENCES operations.entities (tenant_id, id, entity_class_id)
    ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE operations.entity_candidates
    ADD CONSTRAINT uq_entity_candidates_tenant_id UNIQUE (tenant_id, id);
ALTER TABLE operations.entity_candidate_events
    ADD CONSTRAINT fk_candidate_events_tenant_candidate
    FOREIGN KEY (tenant_id, candidate_id)
    REFERENCES operations.entity_candidates (tenant_id, id)
    ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;

CREATE OR REPLACE FUNCTION operations.sync_entity_source_links_from_observations()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = operations, pg_temp
AS $function$
DECLARE
    anchored_clients integer := 0;
    anchored_devices integer := 0;
    inserted_links integer := 0;
    updated_links integer := 0;
    inserted_history integer := 0;
BEGIN
    IF EXISTS (
        SELECT 1
          FROM clients c
          JOIN devices d ON d.id = c.id
         WHERE c.entity_id IS NULL OR d.entity_id IS NULL
    ) THEN
        RAISE EXCEPTION 'Client/device UUID collision prevents safe generic entity anchoring';
    END IF;

    INSERT INTO entities (
        id, tenant_id, entity_class_id, scope_kind, client_id, version,
        created_at, created_reason, updated_at, updated_reason,
        retired_at, retired_reason, deleted_at, deleted_reason
    )
    SELECT c.id, c.tenant_id, 'client', 'tenant', NULL, 1,
           c.created_at, 'system.compatibility_backfill', c.updated_at,
           'system.compatibility_backfill', NULL, '', c.deleted_at,
           c.deleted_reason
      FROM clients c
     WHERE c.entity_id IS NULL
    ON CONFLICT (id) DO NOTHING;

    UPDATE clients c
       SET entity_id = e.id
      FROM entities e
     WHERE c.entity_id IS NULL
       AND e.id = c.id
       AND e.tenant_id = c.tenant_id
       AND e.entity_class_id = 'client';
    GET DIAGNOSTICS anchored_clients = ROW_COUNT;

    INSERT INTO entities (
        id, tenant_id, entity_class_id, scope_kind, client_id, version,
        created_at, created_reason, updated_at, updated_reason,
        retired_at, retired_reason, deleted_at, deleted_reason
    )
    SELECT d.id, d.tenant_id, 'device', 'client', d.client_id, 1,
           d.created_at, 'system.compatibility_backfill', d.updated_at,
           'system.compatibility_backfill',
           CASE WHEN d.lifecycle_status = 'retired' THEN d.updated_at END,
           CASE WHEN d.lifecycle_status = 'retired'
                THEN 'system.compatibility_backfill' ELSE '' END,
           d.deleted_at, d.deleted_reason
      FROM devices d
     WHERE d.entity_id IS NULL
    ON CONFLICT (id) DO NOTHING;

    UPDATE devices d
       SET entity_id = e.id
      FROM entities e
     WHERE d.entity_id IS NULL
       AND e.id = d.id
       AND e.tenant_id = d.tenant_id
       AND e.entity_class_id = 'device';
    GET DIAGNOSTICS anchored_devices = ROW_COUNT;

    CREATE TEMP TABLE IF NOT EXISTS resolved_source_links (
        tenant_id bigint NOT NULL,
        entity_id uuid NOT NULL,
        entity_class_id varchar(80) NOT NULL,
        source_instance_id uuid NOT NULL,
        last_seen_binding_id uuid,
        external_namespace varchar(120) NOT NULL,
        parent_external_namespace varchar(120) NOT NULL,
        parent_external_id text NOT NULL,
        external_id text NOT NULL,
        first_seen_at timestamptz NOT NULL,
        last_seen_at timestamptz NOT NULL,
        missing_since timestamptz,
        PRIMARY KEY (
            tenant_id, source_instance_id, external_namespace,
            parent_external_namespace, parent_external_id, external_id
        )
    ) ON COMMIT DROP;
    TRUNCATE resolved_source_links;

    INSERT INTO resolved_source_links
    WITH first_seen AS (
        SELECT tenant_id, source_instance_id, external_namespace,
               parent_external_namespace, parent_external_id, external_id,
               MIN(effective_from) AS first_seen_at
          FROM entity_observation_history
         GROUP BY tenant_id, source_instance_id, external_namespace,
                  parent_external_namespace, parent_external_id, external_id
    )
    SELECT o.tenant_id,
           COALESCE(d.entity_id, c.entity_id) AS entity_id,
           CASE WHEN d.entity_id IS NOT NULL THEN 'device' ELSE 'client' END,
           o.source_instance_id, o.last_seen_binding_id,
           o.external_namespace, o.parent_external_namespace,
           o.parent_external_id, o.external_id,
           COALESCE(f.first_seen_at, o.observed_at), o.last_seen_at,
           CASE WHEN o.active THEN NULL
                ELSE COALESCE(o.withdrawn_at, o.last_seen_at) END
      FROM entity_observation_current o
      LEFT JOIN devices d
        ON d.tenant_id = o.tenant_id AND d.id = o.device_id
      LEFT JOIN clients c
        ON c.tenant_id = o.tenant_id
       AND c.id = o.client_id
       AND o.device_id IS NULL
       AND o.entity_type = 'org'
      LEFT JOIN first_seen f
        ON f.tenant_id = o.tenant_id
       AND f.source_instance_id = o.source_instance_id
       AND f.external_namespace = o.external_namespace
       AND f.parent_external_namespace = o.parent_external_namespace
       AND f.parent_external_id = o.parent_external_id
       AND f.external_id = o.external_id
     WHERE COALESCE(d.entity_id, c.entity_id) IS NOT NULL;

    UPDATE entity_source_link_history h
       SET effective_to = r.last_seen_at
      FROM entity_source_links l
      JOIN resolved_source_links r
        ON r.tenant_id = l.tenant_id
       AND r.source_instance_id = l.source_instance_id
       AND r.external_namespace = l.external_namespace
       AND r.parent_external_namespace = l.parent_external_namespace
       AND r.parent_external_id = l.parent_external_id
       AND r.external_id = l.external_id
     WHERE h.tenant_id = l.tenant_id
       AND h.source_instance_id = l.source_instance_id
       AND h.external_namespace = l.external_namespace
       AND h.parent_external_namespace = l.parent_external_namespace
       AND h.parent_external_id = l.parent_external_id
       AND h.external_id = l.external_id
       AND h.effective_to IS NULL
       AND (l.entity_id, l.entity_class_id) IS DISTINCT FROM
           (r.entity_id, r.entity_class_id);

    UPDATE entity_source_links l
       SET entity_id = r.entity_id,
           entity_class_id = r.entity_class_id,
           last_seen_binding_id = r.last_seen_binding_id,
           last_seen_at = r.last_seen_at,
           missing_since = r.missing_since,
           match_method = CASE
               WHEN (l.entity_id, l.entity_class_id) IS DISTINCT FROM
                    (r.entity_id, r.entity_class_id)
               THEN 'compatibility' ELSE l.match_method END,
           match_confidence = CASE
               WHEN (l.entity_id, l.entity_class_id) IS DISTINCT FROM
                    (r.entity_id, r.entity_class_id)
               THEN 1 ELSE l.match_confidence END,
           reason = CASE
               WHEN (l.entity_id, l.entity_class_id) IS DISTINCT FROM
                    (r.entity_id, r.entity_class_id)
               THEN 'system.compatibility_reattachment' ELSE l.reason END,
           version = l.version + 1
      FROM resolved_source_links r
     WHERE l.tenant_id = r.tenant_id
       AND l.source_instance_id = r.source_instance_id
       AND l.external_namespace = r.external_namespace
       AND l.parent_external_namespace = r.parent_external_namespace
       AND l.parent_external_id = r.parent_external_id
       AND l.external_id = r.external_id
       AND (l.entity_id, l.entity_class_id, l.last_seen_binding_id,
            l.last_seen_at, l.missing_since) IS DISTINCT FROM
           (r.entity_id, r.entity_class_id, r.last_seen_binding_id,
            r.last_seen_at, r.missing_since);
    GET DIAGNOSTICS updated_links = ROW_COUNT;

    INSERT INTO entity_source_links (
        id, tenant_id, version, entity_id, entity_class_id,
        source_instance_id, last_seen_binding_id, external_namespace,
        parent_external_namespace, parent_external_id, external_id,
        first_seen_at, last_seen_at, missing_since, match_method,
        match_confidence, reason
    )
    SELECT gen_random_uuid(), r.tenant_id, 1, r.entity_id, r.entity_class_id,
           r.source_instance_id, r.last_seen_binding_id,
           r.external_namespace, r.parent_external_namespace,
           r.parent_external_id, r.external_id, r.first_seen_at,
           r.last_seen_at, r.missing_since, 'compatibility', 1,
           'system.compatibility_backfill'
      FROM resolved_source_links r
    ON CONFLICT (
        tenant_id, source_instance_id, external_namespace,
        parent_external_namespace, parent_external_id, external_id
    ) DO NOTHING;
    GET DIAGNOSTICS inserted_links = ROW_COUNT;

    INSERT INTO entity_source_link_history (
        id, tenant_id, version, entity_id, entity_class_id,
        source_instance_id, last_seen_binding_id, external_namespace,
        parent_external_namespace, parent_external_id, external_id,
        match_method, match_confidence, actor_kind, actor_id,
        actor_process, reason, evidence, effective_from, effective_to
    )
    SELECT gen_random_uuid(), l.tenant_id, 1, l.entity_id, l.entity_class_id,
           l.source_instance_id, l.last_seen_binding_id,
           l.external_namespace, l.parent_external_namespace,
           l.parent_external_id, l.external_id, l.match_method,
           l.match_confidence, 'system', NULL, 'ingest.entity_link_sync',
           l.reason, jsonb_build_object('compatibility_projection', TRUE),
           CASE WHEN EXISTS (
               SELECT 1
                 FROM entity_source_link_history prior
                WHERE prior.tenant_id = l.tenant_id
                  AND prior.source_instance_id = l.source_instance_id
                  AND prior.external_namespace = l.external_namespace
                  AND prior.parent_external_namespace = l.parent_external_namespace
                  AND prior.parent_external_id = l.parent_external_id
                  AND prior.external_id = l.external_id
           ) THEN clock_timestamp() ELSE l.first_seen_at END,
           NULL
      FROM entity_source_links l
      LEFT JOIN entity_source_link_history h
        ON h.tenant_id = l.tenant_id
       AND h.source_instance_id = l.source_instance_id
       AND h.external_namespace = l.external_namespace
       AND h.parent_external_namespace = l.parent_external_namespace
       AND h.parent_external_id = l.parent_external_id
       AND h.external_id = l.external_id
       AND h.entity_id = l.entity_id
       AND h.entity_class_id = l.entity_class_id
       AND h.effective_to IS NULL
     WHERE h.id IS NULL;
    GET DIAGNOSTICS inserted_history = ROW_COUNT;

    RETURN jsonb_build_object(
        'anchored_clients', anchored_clients,
        'anchored_devices', anchored_devices,
        'inserted_links', inserted_links,
        'updated_links', updated_links,
        'inserted_history', inserted_history
    );
END;
$function$;

REVOKE ALL ON FUNCTION operations.sync_entity_source_links_from_observations()
    FROM PUBLIC;
GRANT EXECUTE ON FUNCTION operations.sync_entity_source_links_from_observations()
    TO ninja_ingest;
ALTER FUNCTION operations.sync_entity_source_links_from_observations()
    OWNER TO operations_migrate;

SELECT operations.sync_entity_source_links_from_observations();

ALTER TABLE operations.entities ENABLE ROW LEVEL SECURITY;
ALTER TABLE operations.entities FORCE ROW LEVEL SECURITY;
ALTER TABLE operations.entity_source_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE operations.entity_source_links FORCE ROW LEVEL SECURITY;
ALTER TABLE operations.entity_source_link_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE operations.entity_source_link_history FORCE ROW LEVEL SECURITY;
ALTER TABLE operations.entity_candidates ENABLE ROW LEVEL SECURITY;
ALTER TABLE operations.entity_candidates FORCE ROW LEVEL SECURITY;
ALTER TABLE operations.entity_candidate_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE operations.entity_candidate_events FORCE ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON operations.entities
    USING (tenant_id = current_setting('operations.tenant_id', TRUE)::bigint)
    WITH CHECK (tenant_id = current_setting('operations.tenant_id', TRUE)::bigint);
CREATE POLICY tenant_isolation ON operations.entity_source_links
    USING (tenant_id = current_setting('operations.tenant_id', TRUE)::bigint)
    WITH CHECK (tenant_id = current_setting('operations.tenant_id', TRUE)::bigint);
CREATE POLICY tenant_isolation ON operations.entity_source_link_history
    USING (tenant_id = current_setting('operations.tenant_id', TRUE)::bigint)
    WITH CHECK (tenant_id = current_setting('operations.tenant_id', TRUE)::bigint);
CREATE POLICY tenant_isolation ON operations.entity_candidates
    USING (tenant_id = current_setting('operations.tenant_id', TRUE)::bigint)
    WITH CHECK (tenant_id = current_setting('operations.tenant_id', TRUE)::bigint);
CREATE POLICY tenant_isolation ON operations.entity_candidate_events
    USING (tenant_id = current_setting('operations.tenant_id', TRUE)::bigint)
    WITH CHECK (tenant_id = current_setting('operations.tenant_id', TRUE)::bigint);

REVOKE INSERT, UPDATE, DELETE ON operations.entity_classes,
    operations.entity_class_scopes, operations.entity_types FROM operations_app;
GRANT SELECT ON operations.entity_classes, operations.entity_class_scopes
    TO operations_app, ninja_ingest, operations_readonly, metabase_ro;
GRANT SELECT ON operations.entities, operations.entity_source_links,
    operations.entity_source_link_history, operations.entity_candidates,
    operations.entity_candidate_events
    TO operations_app, ninja_ingest, operations_readonly;

ALTER TABLE operations.entity_classes OWNER TO operations_migrate;
ALTER TABLE operations.entity_class_scopes OWNER TO operations_migrate;
ALTER TABLE operations.entities OWNER TO operations_migrate;
ALTER TABLE operations.entity_source_links OWNER TO operations_migrate;
ALTER TABLE operations.entity_source_link_history OWNER TO operations_migrate;
ALTER TABLE operations.entity_candidates OWNER TO operations_migrate;
ALTER TABLE operations.entity_candidate_events OWNER TO operations_migrate;
"""

REVERSE_SQL = r"""
DROP FUNCTION IF EXISTS operations.sync_entity_source_links_from_observations();
ALTER TABLE operations.entity_candidate_events
    DROP CONSTRAINT IF EXISTS fk_candidate_events_tenant_candidate;
ALTER TABLE operations.entity_candidates
    DROP CONSTRAINT IF EXISTS fk_entity_candidates_tenant_source,
    DROP CONSTRAINT IF EXISTS fk_entity_candidates_tenant_client,
    DROP CONSTRAINT IF EXISTS fk_entity_candidates_tenant_proposed,
    DROP CONSTRAINT IF EXISTS fk_entity_candidates_tenant_resolved,
    DROP CONSTRAINT IF EXISTS uq_entity_candidates_tenant_id;
ALTER TABLE operations.entity_source_link_history
    DROP CONSTRAINT IF EXISTS fk_entity_link_hist_tenant_entity_class,
    DROP CONSTRAINT IF EXISTS fk_entity_link_hist_tenant_source,
    DROP CONSTRAINT IF EXISTS fk_entity_link_hist_tenant_binding;
ALTER TABLE operations.entity_source_links
    DROP CONSTRAINT IF EXISTS fk_entity_links_tenant_entity_class,
    DROP CONSTRAINT IF EXISTS fk_entity_links_tenant_source,
    DROP CONSTRAINT IF EXISTS fk_entity_links_tenant_binding;
ALTER TABLE operations.devices DROP CONSTRAINT IF EXISTS fk_devices_tenant_entity;
ALTER TABLE operations.clients DROP CONSTRAINT IF EXISTS fk_clients_tenant_entity;
ALTER TABLE operations.entities
    DROP CONSTRAINT IF EXISTS fk_entities_tenant_client,
    DROP CONSTRAINT IF EXISTS fk_entities_class_scope;
ALTER TABLE operations.source_bindings
    DROP CONSTRAINT IF EXISTS uq_source_bindings_tenant_id;
ALTER TABLE operations.source_instances
    DROP CONSTRAINT IF EXISTS uq_source_instances_tenant_id;
ALTER TABLE operations.devices DROP CONSTRAINT IF EXISTS uq_devices_tenant_id;
ALTER TABLE operations.clients DROP CONSTRAINT IF EXISTS uq_clients_tenant_id;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0100_generic_ninja_and_software_read_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityClass',
            fields=[
                ('name', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'entity_classes',
                'ordering': ('name',),
            },
        ),
        migrations.RunSQL(SEED_ENTITY_CLASSES_SQL, migrations.RunSQL.noop),
        migrations.AddField(
            model_name='entitytype',
            name='consumes_license',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entitytype',
            name='requirement_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope_kind', models.CharField(choices=[('tenant', 'Tenant'), ('client', 'Client')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_reason', models.CharField(blank=True, default='', max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_reason', models.CharField(blank=True, default='', max_length=120)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('retired_reason', models.CharField(blank=True, default='', max_length=120)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_reason', models.CharField(blank=True, default='', max_length=120)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_entities', to='operations.client')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.tenant')),
                ('entity_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entities', to='operations.entityclass')),
            ],
            options={
                'db_table': 'entities',
                'ordering': ('entity_class', 'id'),
            },
        ),
        migrations.AddField(
            model_name='client',
            name='entity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_record', to='operations.entity'),
        ),
        migrations.AddField(
            model_name='device',
            name='entity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='device_record', to='operations.entity'),
        ),
        migrations.CreateModel(
            name='EntityCandidate',
            fields=[
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_namespace', models.CharField(max_length=120)),
                ('parent_external_namespace', models.CharField(blank=True, default='', max_length=120)),
                ('parent_external_id', models.TextField(blank=True, default='')),
                ('external_id', models.TextField()),
                ('status', models.CharField(choices=[('observed_only', 'Observed only'), ('pending', 'Pending'), ('attached', 'Attached'), ('rejected', 'Rejected')], default='observed_only', max_length=24)),
                ('material_hash', models.BinaryField(blank=True, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('latest_decision', models.CharField(blank=True, default='', max_length=32)),
                ('latest_decision_reason', models.TextField(blank=True, default='')),
                ('latest_decided_at', models.DateTimeField(blank=True, null=True)),
                ('first_observed_at', models.DateTimeField()),
                ('last_observed_at', models.DateTimeField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entity_candidates', to='operations.client')),
                ('latest_decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entity_candidate_decisions', to=settings.AUTH_USER_MODEL)),
                ('proposed_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposed_candidates', to='operations.entity')),
                ('resolved_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_candidates', to='operations.entity')),
                ('source_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entity_candidates', to='operations.sourceinstance')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.tenant')),
                ('proposed_entity_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entity_candidates', to='operations.entityclass')),
            ],
            options={
                'db_table': 'entity_candidates',
            },
        ),
        migrations.AddField(
            model_name='entitytype',
            name='entity_class',
            field=models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.PROTECT, related_name='entity_types', to='operations.entityclass'),
        ),
        migrations.CreateModel(
            name='EntityClassScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_kind', models.CharField(choices=[('tenant', 'Tenant'), ('client', 'Client')], max_length=16)),
                ('entity_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='operations.entityclass')),
            ],
            options={
                'db_table': 'entity_class_scopes',
                'ordering': ('entity_class', 'scope_kind'),
            },
        ),
        migrations.CreateModel(
            name='EntitySourceLink',
            fields=[
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_namespace', models.CharField(max_length=120)),
                ('parent_external_namespace', models.CharField(blank=True, default='', max_length=120)),
                ('parent_external_id', models.TextField(blank=True, default='')),
                ('external_id', models.TextField()),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('missing_since', models.DateTimeField(blank=True, null=True)),
                ('match_method', models.CharField(default='compatibility', max_length=32)),
                ('match_confidence', models.DecimalField(decimal_places=3, default=1, max_digits=4)),
                ('reason', models.CharField(blank=True, default='', max_length=120)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_links', to='operations.entity')),
                ('entity_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_links', to='operations.entityclass')),
                ('last_seen_binding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_seen_entity_links', to='operations.sourcebinding')),
                ('source_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entity_links', to='operations.sourceinstance')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.tenant')),
            ],
            options={
                'db_table': 'entity_source_links',
            },
        ),
        migrations.CreateModel(
            name='EntitySourceLinkHistory',
            fields=[
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_namespace', models.CharField(max_length=120)),
                ('parent_external_namespace', models.CharField(blank=True, default='', max_length=120)),
                ('parent_external_id', models.TextField(blank=True, default='')),
                ('external_id', models.TextField()),
                ('match_method', models.CharField(max_length=32)),
                ('match_confidence', models.DecimalField(decimal_places=3, max_digits=4)),
                ('actor_kind', models.CharField(default='system', max_length=16)),
                ('actor_process', models.CharField(blank=True, default='', max_length=120)),
                ('reason', models.CharField(max_length=120)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entity_link_history_events', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_link_history', to='operations.entity')),
                ('entity_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_link_history', to='operations.entityclass')),
                ('last_seen_binding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_link_history', to='operations.sourcebinding')),
                ('source_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entity_link_history', to='operations.sourceinstance')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.tenant')),
            ],
            options={
                'db_table': 'entity_source_link_history',
            },
        ),
        migrations.CreateModel(
            name='EntityCandidateEvent',
            fields=[
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=32)),
                ('actor_kind', models.CharField(default='system', max_length=16)),
                ('actor_process', models.CharField(blank=True, default='', max_length=120)),
                ('reason', models.TextField(blank=True, default='')),
                ('before_state', models.JSONField(blank=True, null=True)),
                ('after_state', models.JSONField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entity_candidate_events', to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='operations.entitycandidate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.tenant')),
            ],
            options={
                'db_table': 'entity_candidate_events',
                'indexes': [models.Index(fields=['tenant', 'candidate', 'occurred_at'], name='idx_entity_candidate_events')],
            },
        ),
        migrations.AddIndex(
            model_name='entitycandidate',
            index=models.Index(fields=['tenant', 'status', 'last_observed_at'], name='idx_entity_candidates_queue'),
        ),
        migrations.AddConstraint(
            model_name='entitycandidate',
            constraint=models.UniqueConstraint(fields=('tenant', 'source_instance', 'external_namespace', 'parent_external_namespace', 'parent_external_id', 'external_id', 'proposed_entity_class'), name='uq_entity_candidates_stable_class'),
        ),
        migrations.AddConstraint(
            model_name='entitycandidate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('external_namespace', ''), _negated=True), models.Q(('external_id', ''), _negated=True), models.Q(models.Q(('parent_external_namespace', ''), ('parent_external_id', '')), models.Q(models.Q(('parent_external_namespace', ''), _negated=True), models.Q(('parent_external_id', ''), _negated=True)), _connector='OR')), name='ck_entity_candidates_stable'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['tenant', 'entity_class', 'client'], name='idx_entities_class_owner'),
        ),
        migrations.AddConstraint(
            model_name='entity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scope_kind', 'tenant'), ('client__isnull', True)), models.Q(('scope_kind', 'client'), ('client__isnull', False)), _connector='OR'), name='ck_entities_scope_owner'),
        ),
        migrations.AddConstraint(
            model_name='entity',
            constraint=models.UniqueConstraint(fields=('tenant', 'id', 'entity_class'), name='uq_entities_tenant_id_class'),
        ),
        migrations.AddConstraint(
            model_name='entity',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_entities_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='entityclassscope',
            constraint=models.UniqueConstraint(fields=('entity_class', 'scope_kind'), name='uq_entity_class_scopes_class_scope'),
        ),
        migrations.AddIndex(
            model_name='entitysourcelink',
            index=models.Index(fields=['tenant', 'entity', 'entity_class'], name='idx_entity_source_links_entity'),
        ),
        migrations.AddIndex(
            model_name='entitysourcelink',
            index=models.Index(fields=['tenant', 'missing_since'], name='idx_entity_links_missing'),
        ),
        migrations.AddConstraint(
            model_name='entitysourcelink',
            constraint=models.UniqueConstraint(fields=('tenant', 'source_instance', 'external_namespace', 'parent_external_namespace', 'parent_external_id', 'external_id'), name='uq_entity_source_links_stable'),
        ),
        migrations.AddConstraint(
            model_name='entitysourcelink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('external_namespace', ''), _negated=True), models.Q(('external_id', ''), _negated=True), models.Q(models.Q(('parent_external_namespace', ''), ('parent_external_id', '')), models.Q(models.Q(('parent_external_namespace', ''), _negated=True), models.Q(('parent_external_id', ''), _negated=True)), _connector='OR')), name='ck_entity_source_links_stable'),
        ),
        migrations.AddIndex(
            model_name='entitysourcelinkhistory',
            index=models.Index(fields=['tenant', 'entity', 'effective_from'], name='idx_entity_link_hist_entity'),
        ),
        migrations.AddIndex(
            model_name='entitysourcelinkhistory',
            index=models.Index(fields=['tenant', 'effective_to'], name='idx_entity_link_hist_retention'),
        ),
        migrations.AddConstraint(
            model_name='entitysourcelinkhistory',
            constraint=models.UniqueConstraint(condition=models.Q(('effective_to__isnull', True)), fields=('tenant', 'source_instance', 'external_namespace', 'parent_external_namespace', 'parent_external_id', 'external_id'), name='uq_entity_source_link_history_open'),
        ),
        migrations.AddConstraint(
            model_name='entitysourcelinkhistory',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('external_namespace', ''), _negated=True), models.Q(('external_id', ''), _negated=True), models.Q(models.Q(('parent_external_namespace', ''), ('parent_external_id', '')), models.Q(models.Q(('parent_external_namespace', ''), _negated=True), models.Q(('parent_external_id', ''), _negated=True)), _connector='OR')), name='ck_entity_link_history_stable'),
        ),
        migrations.AddConstraint(
            model_name='entitysourcelinkhistory',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='ck_entity_link_history_window'),
        ),
        migrations.RunSQL(FORWARD_SQL, REVERSE_SQL),
    ]
