# Generated by Django 5.1.15 on 2026-08-04 13:23

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0101_generic_entity_source_link_kernel"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityAttributeClaimEvidence",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("entity_id", models.UUIDField()),
                ("entity_class", models.CharField(max_length=80)),
                ("observation_id", models.UUIDField()),
                ("source_instance_id", models.UUIDField()),
                ("attribute_key", models.CharField(max_length=120)),
                ("attribute_display_name", models.CharField(max_length=160)),
                ("sensitivity", models.CharField(max_length=16)),
                ("cardinality", models.CharField(max_length=12)),
                ("value_display", models.TextField()),
                ("authority_eligible", models.BooleanField()),
                ("authority_tier", models.PositiveSmallIntegerField()),
                ("authority_priority", models.PositiveSmallIntegerField()),
                ("first_observed_at", models.DateTimeField()),
                ("last_observed_at", models.DateTimeField()),
            ],
            options={
                "db_table": "v_entity_attribute_claim_current",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EntityAttributeClaimStorageStatus",
            fields=[
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="operations.tenant",
                    ),
                ),
                ("current_claim_rows", models.BigIntegerField()),
                ("active_claim_rows", models.BigIntegerField()),
                ("history_claim_rows", models.BigIntegerField()),
                ("changed_members_1d", models.BigIntegerField()),
                ("partition_review_required", models.BooleanField()),
            ],
            options={
                "db_table": "v_entity_attribute_claim_storage_status",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AttributeDefinition",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("key", models.CharField(max_length=120)),
                ("display_name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("boolean", "Boolean"),
                            ("timestamp", "Timestamp"),
                            ("entity_reference", "Entity reference"),
                            ("structured", "Structured detail"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "cardinality",
                    models.CharField(choices=[("single", "Single"), ("set", "Set")], max_length=12),
                ),
                (
                    "sensitivity",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("internal", "Internal"),
                            ("sensitive", "Sensitive"),
                            ("restricted", "Restricted"),
                        ],
                        default="restricted",
                        max_length=16,
                    ),
                ),
                ("validation", models.JSONField(blank=True, default=dict)),
                ("canonical_projection_eligible", models.BooleanField(default=False)),
                (
                    "single_value_conflict_policy",
                    models.CharField(
                        choices=[
                            ("retain_last_uncontested", "Retain last uncontested"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                (
                    "set_merge_policy",
                    models.CharField(
                        choices=[
                            ("highest_authority_union", "Highest-authority union"),
                            ("all_eligible_union", "All-eligible union"),
                        ],
                        default="highest_authority_union",
                        max_length=32,
                    ),
                ),
                ("definition_version", models.PositiveIntegerField(default=1)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "entity_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attribute_definitions",
                        to="operations.entityclass",
                    ),
                ),
            ],
            options={
                "db_table": "attribute_definitions",
                "ordering": ("entity_class", "key", "-definition_version"),
            },
        ),
        migrations.CreateModel(
            name="AttributeAuthorityPolicy",
            fields=[
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("native_record_type", models.CharField(max_length=80)),
                ("eligible", models.BooleanField(default=False)),
                ("authority_tier", models.PositiveSmallIntegerField(default=0)),
                ("priority", models.PositiveSmallIntegerField(default=0)),
                ("enabled", models.BooleanField(default=True)),
                ("reason", models.CharField(blank=True, default="", max_length=160)),
                (
                    "source_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attribute_authority_policies",
                        to="operations.sourceinstance",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="operations.tenant"),
                ),
                (
                    "attribute_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authority_policies",
                        to="operations.attributedefinition",
                    ),
                ),
            ],
            options={
                "db_table": "attribute_authority_policies",
            },
        ),
        migrations.CreateModel(
            name="EntityAttributeClaimCurrent",
            fields=[
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("boolean", "Boolean"),
                            ("timestamp", "Timestamp"),
                            ("entity_reference", "Entity reference"),
                            ("structured", "Structured detail"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "cardinality",
                    models.CharField(choices=[("single", "Single"), ("set", "Set")], max_length=12),
                ),
                ("value_text", models.TextField(blank=True, null=True)),
                (
                    "value_number",
                    models.DecimalField(blank=True, decimal_places=10, max_digits=38, null=True),
                ),
                ("value_boolean", models.BooleanField(blank=True, null=True)),
                ("value_timestamp", models.DateTimeField(blank=True, null=True)),
                ("value_json", models.JSONField(blank=True, null=True)),
                ("value_fingerprint", models.BinaryField()),
                ("member_key", models.BinaryField()),
                ("mapping_version", models.PositiveIntegerField()),
                ("authority_eligible", models.BooleanField(default=False)),
                ("authority_tier", models.PositiveSmallIntegerField(default=0)),
                ("authority_priority", models.PositiveSmallIntegerField(default=0)),
                ("first_observed_at", models.DateTimeField()),
                ("last_observed_at", models.DateTimeField()),
                ("active", models.BooleanField(default=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                (
                    "attribute_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="current_claims",
                        to="operations.attributedefinition",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attribute_claims",
                        to="operations.entity",
                    ),
                ),
                (
                    "entity_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attribute_claims",
                        to="operations.entityclass",
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attribute_claims",
                        to="operations.entityobservationcurrent",
                    ),
                ),
                (
                    "source_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attribute_claims",
                        to="operations.sourceinstance",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="operations.tenant"),
                ),
                (
                    "value_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referenced_attribute_claims",
                        to="operations.entity",
                    ),
                ),
            ],
            options={
                "db_table": "entity_attribute_claim_current",
            },
        ),
        migrations.CreateModel(
            name="EntityAttributeProjectionState",
            fields=[
                (
                    "observation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="attribute_projection_state",
                        serialize=False,
                        to="operations.entityobservationcurrent",
                    ),
                ),
                ("projection_hash", models.BinaryField()),
                ("observation_active", models.BooleanField()),
                ("projection_contract_version", models.PositiveIntegerField(default=1)),
                ("projected_at", models.DateTimeField()),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attribute_projection_states",
                        to="operations.entity",
                    ),
                ),
                (
                    "entity_source_link",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attribute_projection_states",
                        to="operations.entitysourcelink",
                    ),
                ),
                (
                    "source_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attribute_projection_states",
                        to="operations.sourceinstance",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="operations.tenant"),
                ),
            ],
            options={
                "db_table": "entity_attribute_projection_state",
            },
        ),
        migrations.CreateModel(
            name="EntityAttributeWithheldCurrent",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("observed_field_count", models.PositiveIntegerField(default=0)),
                ("mapped_field_count", models.PositiveIntegerField(default=0)),
                ("unmapped_field_count", models.PositiveIntegerField(default=0)),
                ("restricted_field_count", models.PositiveIntegerField(default=0)),
                ("invalid_field_count", models.PositiveIntegerField(default=0)),
                ("projected_claim_count", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("projection_contract_version", models.PositiveIntegerField(default=1)),
                ("measured_at", models.DateTimeField()),
                (
                    "observation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attribute_withheld_counts",
                        to="operations.entityobservationcurrent",
                    ),
                ),
                (
                    "source_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attribute_withheld_counts",
                        to="operations.sourceinstance",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="operations.tenant"),
                ),
            ],
            options={
                "db_table": "entity_attribute_withheld_current",
            },
        ),
        migrations.CreateModel(
            name="IdentityAuthorityPolicy",
            fields=[
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("native_record_type", models.CharField(max_length=80)),
                ("may_establish_identity", models.BooleanField(default=False)),
                ("may_create_canonical", models.BooleanField(default=False)),
                ("enabled", models.BooleanField(default=True)),
                ("reason", models.CharField(blank=True, default="", max_length=160)),
                (
                    "resulting_entity_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="identity_authority_policies",
                        to="operations.entitytype",
                    ),
                ),
                (
                    "source_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="identity_authority_policies",
                        to="operations.sourceinstance",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="operations.tenant"),
                ),
            ],
            options={
                "db_table": "identity_authority_policies",
            },
        ),
        migrations.CreateModel(
            name="SourceFieldMapping",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("external_namespace", models.CharField(blank=True, default="", max_length=120)),
                ("native_record_type", models.CharField(blank=True, default="", max_length=80)),
                (
                    "document_kind",
                    models.CharField(
                        choices=[
                            ("canonical", "Normalized source record"),
                            ("raw", "Raw source record"),
                        ],
                        default="canonical",
                        max_length=16,
                    ),
                ),
                ("source_field", models.CharField(max_length=160)),
                ("mapping_version", models.PositiveIntegerField(default=1)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "attribute_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_mappings",
                        to="operations.attributedefinition",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attribute_field_mappings",
                        to="operations.source",
                    ),
                ),
            ],
            options={
                "db_table": "source_field_mappings",
                "ordering": (
                    "source",
                    "external_namespace",
                    "native_record_type",
                    "document_kind",
                    "source_field",
                    "-mapping_version",
                ),
            },
        ),
        migrations.CreateModel(
            name="EntityAttributeClaimHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("boolean", "Boolean"),
                            ("timestamp", "Timestamp"),
                            ("entity_reference", "Entity reference"),
                            ("structured", "Structured detail"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "cardinality",
                    models.CharField(choices=[("single", "Single"), ("set", "Set")], max_length=12),
                ),
                ("value_text", models.TextField(blank=True, null=True)),
                (
                    "value_number",
                    models.DecimalField(blank=True, decimal_places=10, max_digits=38, null=True),
                ),
                ("value_boolean", models.BooleanField(blank=True, null=True)),
                ("value_timestamp", models.DateTimeField(blank=True, null=True)),
                ("value_json", models.JSONField(blank=True, null=True)),
                ("value_fingerprint", models.BinaryField()),
                ("member_key", models.BinaryField()),
                ("mapping_version", models.PositiveIntegerField()),
                ("authority_eligible", models.BooleanField(default=False)),
                ("authority_tier", models.PositiveSmallIntegerField(default=0)),
                ("authority_priority", models.PositiveSmallIntegerField(default=0)),
                ("effective_from", models.DateTimeField()),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("closed_reason", models.CharField(blank=True, default="", max_length=40)),
                (
                    "attribute_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="claim_history",
                        to="operations.attributedefinition",
                    ),
                ),
                (
                    "current_claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="history",
                        to="operations.entityattributeclaimcurrent",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attribute_claim_history",
                        to="operations.entity",
                    ),
                ),
                (
                    "entity_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attribute_claim_history",
                        to="operations.entityclass",
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attribute_claim_history",
                        to="operations.entityobservationcurrent",
                    ),
                ),
                (
                    "source_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attribute_claim_history",
                        to="operations.sourceinstance",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="operations.tenant"),
                ),
                (
                    "value_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referenced_attribute_claim_history",
                        to="operations.entity",
                    ),
                ),
                (
                    "source_mapping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="claim_history",
                        to="operations.sourcefieldmapping",
                    ),
                ),
            ],
            options={
                "db_table": "entity_attribute_claim_history",
            },
        ),
        migrations.AddField(
            model_name="entityattributeclaimcurrent",
            name="source_mapping",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="current_claims",
                to="operations.sourcefieldmapping",
            ),
        ),
        migrations.AddConstraint(
            model_name="attributedefinition",
            constraint=models.UniqueConstraint(
                fields=("entity_class", "key", "definition_version"),
                name="uq_attr_defs_class_key_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="attributedefinition",
            constraint=models.UniqueConstraint(
                condition=models.Q(("enabled", True)),
                fields=("entity_class", "key"),
                name="uq_attr_defs_enabled_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="attributedefinition",
            constraint=models.UniqueConstraint(
                fields=("id", "value_type", "cardinality"), name="uq_attr_defs_typed_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="attributeauthoritypolicy",
            constraint=models.UniqueConstraint(
                fields=("tenant", "source_instance", "native_record_type", "attribute_definition"),
                name="uq_attribute_authority_policy",
            ),
        ),
        migrations.AddIndex(
            model_name="entityattributeprojectionstate",
            index=models.Index(
                fields=["tenant", "source_instance", "observation_active"],
                name="idx_attr_projection_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="entityattributeprojectionstate",
            constraint=models.UniqueConstraint(fields=("tenant", "observation"), name="uq_attr_projection_tenant_obs"),
        ),
        migrations.AddIndex(
            model_name="entityattributewithheldcurrent",
            index=models.Index(
                fields=["tenant", "active", "unmapped_field_count"],
                name="idx_attr_withheld_unmapped",
            ),
        ),
        migrations.AddConstraint(
            model_name="entityattributewithheldcurrent",
            constraint=models.UniqueConstraint(fields=("tenant", "observation"), name="uq_attr_withheld_tenant_obs"),
        ),
        migrations.AddConstraint(
            model_name="identityauthoritypolicy",
            constraint=models.UniqueConstraint(
                fields=("tenant", "source_instance", "native_record_type", "resulting_entity_type"),
                name="uq_identity_authority_policy",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcefieldmapping",
            constraint=models.UniqueConstraint(
                fields=(
                    "source",
                    "external_namespace",
                    "native_record_type",
                    "document_kind",
                    "source_field",
                    "mapping_version",
                ),
                name="uq_source_field_mapping_version",
                nulls_distinct=False,
            ),
        ),
        migrations.AddIndex(
            model_name="entityattributeclaimhistory",
            index=models.Index(
                fields=["tenant", "entity", "attribute_definition", "effective_from"],
                name="idx_attr_claim_history_entity",
            ),
        ),
        migrations.AddIndex(
            model_name="entityattributeclaimhistory",
            index=models.Index(fields=["tenant", "effective_to"], name="idx_attr_claim_hist_retention"),
        ),
        migrations.AddConstraint(
            model_name="entityattributeclaimhistory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("effective_to__isnull", True)),
                fields=("tenant", "current_claim"),
                name="uq_attr_claim_history_open",
            ),
        ),
        migrations.AddConstraint(
            model_name="entityattributeclaimhistory",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("pk__isnull", True),
                    models.Q(
                        ("value_type", "text"),
                        ("value_text__isnull", False),
                        ("value_number__isnull", True),
                        ("value_boolean__isnull", True),
                        ("value_timestamp__isnull", True),
                        ("value_entity__isnull", True),
                        ("value_json__isnull", True),
                    ),
                    models.Q(
                        ("value_type", "number"),
                        ("value_text__isnull", True),
                        ("value_number__isnull", False),
                        ("value_boolean__isnull", True),
                        ("value_timestamp__isnull", True),
                        ("value_entity__isnull", True),
                        ("value_json__isnull", True),
                    ),
                    models.Q(
                        ("value_type", "boolean"),
                        ("value_text__isnull", True),
                        ("value_number__isnull", True),
                        ("value_boolean__isnull", False),
                        ("value_timestamp__isnull", True),
                        ("value_entity__isnull", True),
                        ("value_json__isnull", True),
                    ),
                    models.Q(
                        ("value_type", "timestamp"),
                        ("value_text__isnull", True),
                        ("value_number__isnull", True),
                        ("value_boolean__isnull", True),
                        ("value_timestamp__isnull", False),
                        ("value_entity__isnull", True),
                        ("value_json__isnull", True),
                    ),
                    models.Q(
                        ("value_type", "entity_reference"),
                        ("value_text__isnull", True),
                        ("value_number__isnull", True),
                        ("value_boolean__isnull", True),
                        ("value_timestamp__isnull", True),
                        ("value_entity__isnull", False),
                        ("value_json__isnull", True),
                    ),
                    models.Q(
                        ("value_type", "structured"),
                        ("value_text__isnull", True),
                        ("value_number__isnull", True),
                        ("value_boolean__isnull", True),
                        ("value_timestamp__isnull", True),
                        ("value_entity__isnull", True),
                        ("value_json__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="ck_attr_claim_history_typed_value",
            ),
        ),
        migrations.AddIndex(
            model_name="entityattributeclaimcurrent",
            index=models.Index(
                fields=["tenant", "entity", "attribute_definition", "active"],
                name="idx_attr_claim_current_entity",
            ),
        ),
        migrations.AddIndex(
            model_name="entityattributeclaimcurrent",
            index=models.Index(fields=["tenant", "observation", "active"], name="idx_attr_claim_current_obs"),
        ),
        migrations.AddConstraint(
            model_name="entityattributeclaimcurrent",
            constraint=models.UniqueConstraint(
                fields=("tenant", "observation", "attribute_definition", "member_key"),
                name="uq_attr_claim_current_member",
            ),
        ),
        migrations.AddConstraint(
            model_name="entityattributeclaimcurrent",
            constraint=models.UniqueConstraint(fields=("tenant", "id"), name="uq_attr_claim_current_tenant_id"),
        ),
        migrations.AddConstraint(
            model_name="entityattributeclaimcurrent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("pk__isnull", True),
                    models.Q(
                        ("value_type", "text"),
                        ("value_text__isnull", False),
                        ("value_number__isnull", True),
                        ("value_boolean__isnull", True),
                        ("value_timestamp__isnull", True),
                        ("value_entity__isnull", True),
                        ("value_json__isnull", True),
                    ),
                    models.Q(
                        ("value_type", "number"),
                        ("value_text__isnull", True),
                        ("value_number__isnull", False),
                        ("value_boolean__isnull", True),
                        ("value_timestamp__isnull", True),
                        ("value_entity__isnull", True),
                        ("value_json__isnull", True),
                    ),
                    models.Q(
                        ("value_type", "boolean"),
                        ("value_text__isnull", True),
                        ("value_number__isnull", True),
                        ("value_boolean__isnull", False),
                        ("value_timestamp__isnull", True),
                        ("value_entity__isnull", True),
                        ("value_json__isnull", True),
                    ),
                    models.Q(
                        ("value_type", "timestamp"),
                        ("value_text__isnull", True),
                        ("value_number__isnull", True),
                        ("value_boolean__isnull", True),
                        ("value_timestamp__isnull", False),
                        ("value_entity__isnull", True),
                        ("value_json__isnull", True),
                    ),
                    models.Q(
                        ("value_type", "entity_reference"),
                        ("value_text__isnull", True),
                        ("value_number__isnull", True),
                        ("value_boolean__isnull", True),
                        ("value_timestamp__isnull", True),
                        ("value_entity__isnull", False),
                        ("value_json__isnull", True),
                    ),
                    models.Q(
                        ("value_type", "structured"),
                        ("value_text__isnull", True),
                        ("value_number__isnull", True),
                        ("value_boolean__isnull", True),
                        ("value_timestamp__isnull", True),
                        ("value_entity__isnull", True),
                        ("value_json__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="ck_attr_claim_current_typed_value",
            ),
        ),
        migrations.AddConstraint(
            model_name="entityattributeclaimcurrent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("active", True), ("withdrawn_at__isnull", True)),
                    models.Q(("active", False), ("withdrawn_at__isnull", False)),
                    _connector="OR",
                ),
                name="ck_attr_claim_current_presence",
            ),
        ),
    ]
