# Generated by Django 5.1.15 on 2026-08-04 15:15

import uuid
from typing import ClassVar

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("operations", "0106_use_source_material_hash_for_claim_projection"),
    ]

    operations: ClassVar[list] = [
        migrations.CreateModel(
            name="EntityAttributeConflictCurrent",
            fields=[
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("conflict_kind", models.CharField(default="equal_authority", max_length=40)),
                ("authority_tier", models.PositiveSmallIntegerField()),
                ("authority_priority", models.PositiveSmallIntegerField()),
                ("conflicting_value_count", models.PositiveIntegerField()),
                ("first_detected_at", models.DateTimeField()),
                ("last_detected_at", models.DateTimeField()),
                (
                    "attribute_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="current_conflicts",
                        to="operations.attributedefinition",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attribute_conflicts",
                        to="operations.entity",
                    ),
                ),
                (
                    "entity_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attribute_conflicts",
                        to="operations.entityclass",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="operations.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "entity_attribute_conflict_current",
            },
        ),
        migrations.CreateModel(
            name="EntityAttributeConflictClaimSupport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conflict_support",
                        to="operations.entityattributeclaimcurrent",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="operations.tenant"
                    ),
                ),
                (
                    "conflict",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claim_support",
                        to="operations.entityattributeconflictcurrent",
                    ),
                ),
            ],
            options={
                "db_table": "entity_attribute_conflict_claim_support",
            },
        ),
        migrations.CreateModel(
            name="EntityAttributeDecisionCurrent",
            fields=[
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("replace", "Replace"),
                            ("clear", "Clear"),
                            ("modify", "Modify set"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("boolean", "Boolean"),
                            ("timestamp", "Timestamp"),
                            ("entity_reference", "Entity reference"),
                            ("structured", "Structured detail"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "cardinality",
                    models.CharField(choices=[("single", "Single"), ("set", "Set")], max_length=12),
                ),
                ("value_text", models.TextField(blank=True, null=True)),
                (
                    "value_number",
                    models.DecimalField(blank=True, decimal_places=10, max_digits=38, null=True),
                ),
                ("value_boolean", models.BooleanField(blank=True, null=True)),
                ("value_timestamp", models.DateTimeField(blank=True, null=True)),
                ("value_json", models.JSONField(blank=True, null=True)),
                ("value_fingerprint", models.BinaryField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("reason", models.TextField()),
                ("decided_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                (
                    "attribute_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operator_decisions",
                        to="operations.attributedefinition",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attribute_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attribute_decisions",
                        to="operations.entity",
                    ),
                ),
                (
                    "entity_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attribute_decisions",
                        to="operations.entityclass",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="operations.tenant"
                    ),
                ),
                (
                    "value_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referenced_attribute_decisions",
                        to="operations.entity",
                    ),
                ),
            ],
            options={
                "db_table": "entity_attribute_decision_current",
            },
        ),
        migrations.CreateModel(
            name="EntityAttributeDecisionMemberCurrent",
            fields=[
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action",
                    models.CharField(choices=[("add", "Add"), ("remove", "Remove")], max_length=12),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("boolean", "Boolean"),
                            ("timestamp", "Timestamp"),
                            ("entity_reference", "Entity reference"),
                            ("structured", "Structured detail"),
                        ],
                        max_length=24,
                    ),
                ),
                ("value_text", models.TextField(blank=True, null=True)),
                (
                    "value_number",
                    models.DecimalField(blank=True, decimal_places=10, max_digits=38, null=True),
                ),
                ("value_boolean", models.BooleanField(blank=True, null=True)),
                ("value_timestamp", models.DateTimeField(blank=True, null=True)),
                ("value_json", models.JSONField(blank=True, null=True)),
                ("value_fingerprint", models.BinaryField()),
                ("member_key", models.BinaryField()),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="operations.entityattributedecisioncurrent",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="operations.tenant"
                    ),
                ),
                (
                    "value_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referenced_attribute_decision_members",
                        to="operations.entity",
                    ),
                ),
            ],
            options={
                "db_table": "entity_attribute_decision_member_current",
            },
        ),
        migrations.CreateModel(
            name="EntityAttributeEffectiveCurrent",
            fields=[
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("boolean", "Boolean"),
                            ("timestamp", "Timestamp"),
                            ("entity_reference", "Entity reference"),
                            ("structured", "Structured detail"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "cardinality",
                    models.CharField(choices=[("single", "Single"), ("set", "Set")], max_length=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("selected", "Selected"),
                            ("cleared", "Cleared by operator"),
                            ("empty", "Empty set"),
                            ("unknown", "Unknown due to conflict"),
                            ("no_evidence", "No eligible evidence"),
                        ],
                        max_length=20,
                    ),
                ),
                ("selection_reason", models.CharField(max_length=40)),
                ("value_text", models.TextField(blank=True, null=True)),
                (
                    "value_number",
                    models.DecimalField(blank=True, decimal_places=10, max_digits=38, null=True),
                ),
                ("value_boolean", models.BooleanField(blank=True, null=True)),
                ("value_timestamp", models.DateTimeField(blank=True, null=True)),
                ("value_json", models.JSONField(blank=True, null=True)),
                ("value_fingerprint", models.BinaryField(blank=True, null=True)),
                (
                    "selected_authority_tier",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "selected_authority_priority",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("conflict", models.BooleanField(default=False)),
                ("input_hash", models.BinaryField()),
                ("projected_at", models.DateTimeField()),
                (
                    "attribute_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="effective_values",
                        to="operations.attributedefinition",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="effective_attributes",
                        to="operations.entity",
                    ),
                ),
                (
                    "entity_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="effective_attributes",
                        to="operations.entityclass",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="operations.tenant"
                    ),
                ),
                (
                    "value_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referenced_effective_attributes",
                        to="operations.entity",
                    ),
                ),
            ],
            options={
                "db_table": "entity_attribute_effective_current",
            },
        ),
        migrations.CreateModel(
            name="EntityAttributeEffectiveDirty",
            fields=[
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("queued_at", models.DateTimeField()),
                ("reason", models.CharField(max_length=40)),
                (
                    "attribute_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dirty_effective_values",
                        to="operations.attributedefinition",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dirty_effective_attributes",
                        to="operations.entity",
                    ),
                ),
                (
                    "entity_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dirty_effective_attributes",
                        to="operations.entityclass",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="operations.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "entity_attribute_effective_dirty",
            },
        ),
        migrations.CreateModel(
            name="EntityAttributeEffectiveMemberCurrent",
            fields=[
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("boolean", "Boolean"),
                            ("timestamp", "Timestamp"),
                            ("entity_reference", "Entity reference"),
                            ("structured", "Structured detail"),
                        ],
                        max_length=24,
                    ),
                ),
                ("value_text", models.TextField(blank=True, null=True)),
                (
                    "value_number",
                    models.DecimalField(blank=True, decimal_places=10, max_digits=38, null=True),
                ),
                ("value_boolean", models.BooleanField(blank=True, null=True)),
                ("value_timestamp", models.DateTimeField(blank=True, null=True)),
                ("value_json", models.JSONField(blank=True, null=True)),
                ("value_fingerprint", models.BinaryField()),
                ("member_key", models.BinaryField()),
                ("selection_reason", models.CharField(max_length=40)),
                (
                    "effective",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="operations.entityattributeeffectivecurrent",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="operations.tenant"
                    ),
                ),
                (
                    "value_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referenced_effective_attribute_members",
                        to="operations.entity",
                    ),
                ),
            ],
            options={
                "db_table": "entity_attribute_effective_member_current",
            },
        ),
        migrations.CreateModel(
            name="EntityAttributeEffectiveClaimSupport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="effective_support",
                        to="operations.entityattributeclaimcurrent",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="operations.tenant"
                    ),
                ),
                (
                    "effective",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claim_support",
                        to="operations.entityattributeeffectivecurrent",
                    ),
                ),
                (
                    "effective_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claim_support",
                        to="operations.entityattributeeffectivemembercurrent",
                    ),
                ),
            ],
            options={
                "db_table": "entity_attribute_effective_claim_support",
            },
        ),
        migrations.AddIndex(
            model_name="entityattributeconflictcurrent",
            index=models.Index(
                fields=["tenant", "entity", "attribute_definition"], name="idx_attr_conflict_entity"
            ),
        ),
        migrations.AddConstraint(
            model_name="entityattributeconflictcurrent",
            constraint=models.UniqueConstraint(
                fields=("tenant", "entity", "attribute_definition"), name="uq_attr_conflict_current"
            ),
        ),
        migrations.AddConstraint(
            model_name="entityattributeconflictcurrent",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_attr_conflict_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="entityattributeconflictcurrent",
            constraint=models.CheckConstraint(
                condition=models.Q(("conflicting_value_count__gte", 2)),
                name="ck_attr_conflict_multiple_values",
            ),
        ),
        migrations.AddConstraint(
            model_name="entityattributeconflictclaimsupport",
            constraint=models.UniqueConstraint(
                fields=("tenant", "conflict", "claim"), name="uq_attr_conflict_claim_support"
            ),
        ),
        migrations.AddIndex(
            model_name="entityattributedecisioncurrent",
            index=models.Index(
                fields=["tenant", "entity", "attribute_definition", "active"],
                name="idx_attr_decision_entity",
            ),
        ),
        migrations.AddConstraint(
            model_name="entityattributedecisioncurrent",
            constraint=models.UniqueConstraint(
                fields=("tenant", "entity", "attribute_definition"), name="uq_attr_decision_current"
            ),
        ),
        migrations.AddConstraint(
            model_name="entityattributedecisioncurrent",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_attr_decision_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="entityattributedecisioncurrent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("cardinality", "single"),
                        ("operation", "replace"),
                        ("value_fingerprint__isnull", False),
                        models.Q(
                            ("pk__isnull", True),
                            models.Q(
                                ("value_type", "text"),
                                ("value_text__isnull", False),
                                ("value_number__isnull", True),
                                ("value_boolean__isnull", True),
                                ("value_timestamp__isnull", True),
                                ("value_entity__isnull", True),
                                ("value_json__isnull", True),
                            ),
                            models.Q(
                                ("value_type", "number"),
                                ("value_text__isnull", True),
                                ("value_number__isnull", False),
                                ("value_boolean__isnull", True),
                                ("value_timestamp__isnull", True),
                                ("value_entity__isnull", True),
                                ("value_json__isnull", True),
                            ),
                            models.Q(
                                ("value_type", "boolean"),
                                ("value_text__isnull", True),
                                ("value_number__isnull", True),
                                ("value_boolean__isnull", False),
                                ("value_timestamp__isnull", True),
                                ("value_entity__isnull", True),
                                ("value_json__isnull", True),
                            ),
                            models.Q(
                                ("value_type", "timestamp"),
                                ("value_text__isnull", True),
                                ("value_number__isnull", True),
                                ("value_boolean__isnull", True),
                                ("value_timestamp__isnull", False),
                                ("value_entity__isnull", True),
                                ("value_json__isnull", True),
                            ),
                            models.Q(
                                ("value_type", "entity_reference"),
                                ("value_text__isnull", True),
                                ("value_number__isnull", True),
                                ("value_boolean__isnull", True),
                                ("value_timestamp__isnull", True),
                                ("value_entity__isnull", False),
                                ("value_json__isnull", True),
                            ),
                            models.Q(
                                ("value_type", "structured"),
                                ("value_text__isnull", True),
                                ("value_number__isnull", True),
                                ("value_boolean__isnull", True),
                                ("value_timestamp__isnull", True),
                                ("value_entity__isnull", True),
                                ("value_json__isnull", False),
                            ),
                            _connector="OR",
                        ),
                    ),
                    models.Q(
                        ("cardinality", "single"),
                        ("operation", "clear"),
                        ("value_fingerprint__isnull", True),
                        ("value_text__isnull", True),
                        ("value_number__isnull", True),
                        ("value_boolean__isnull", True),
                        ("value_timestamp__isnull", True),
                        ("value_entity__isnull", True),
                        ("value_json__isnull", True),
                    ),
                    models.Q(
                        ("cardinality", "set"),
                        ("operation__in", ("replace", "modify")),
                        ("value_fingerprint__isnull", True),
                        ("value_text__isnull", True),
                        ("value_number__isnull", True),
                        ("value_boolean__isnull", True),
                        ("value_timestamp__isnull", True),
                        ("value_entity__isnull", True),
                        ("value_json__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="ck_attr_decision_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="entityattributedecisionmembercurrent",
            constraint=models.UniqueConstraint(
                fields=("tenant", "decision", "member_key"), name="uq_attr_decision_member"
            ),
        ),
        migrations.AddConstraint(
            model_name="entityattributedecisionmembercurrent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("pk__isnull", True),
                    models.Q(
                        ("value_type", "text"),
                        ("value_text__isnull", False),
                        ("value_number__isnull", True),
                        ("value_boolean__isnull", True),
                        ("value_timestamp__isnull", True),
                        ("value_entity__isnull", True),
                        ("value_json__isnull", True),
                    ),
                    models.Q(
                        ("value_type", "number"),
                        ("value_text__isnull", True),
                        ("value_number__isnull", False),
                        ("value_boolean__isnull", True),
                        ("value_timestamp__isnull", True),
                        ("value_entity__isnull", True),
                        ("value_json__isnull", True),
                    ),
                    models.Q(
                        ("value_type", "boolean"),
                        ("value_text__isnull", True),
                        ("value_number__isnull", True),
                        ("value_boolean__isnull", False),
                        ("value_timestamp__isnull", True),
                        ("value_entity__isnull", True),
                        ("value_json__isnull", True),
                    ),
                    models.Q(
                        ("value_type", "timestamp"),
                        ("value_text__isnull", True),
                        ("value_number__isnull", True),
                        ("value_boolean__isnull", True),
                        ("value_timestamp__isnull", False),
                        ("value_entity__isnull", True),
                        ("value_json__isnull", True),
                    ),
                    models.Q(
                        ("value_type", "entity_reference"),
                        ("value_text__isnull", True),
                        ("value_number__isnull", True),
                        ("value_boolean__isnull", True),
                        ("value_timestamp__isnull", True),
                        ("value_entity__isnull", False),
                        ("value_json__isnull", True),
                    ),
                    models.Q(
                        ("value_type", "structured"),
                        ("value_text__isnull", True),
                        ("value_number__isnull", True),
                        ("value_boolean__isnull", True),
                        ("value_timestamp__isnull", True),
                        ("value_entity__isnull", True),
                        ("value_json__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="ck_attr_decision_member_typed_value",
            ),
        ),
        migrations.AddIndex(
            model_name="entityattributeeffectivecurrent",
            index=models.Index(
                fields=["tenant", "entity", "attribute_definition", "status"],
                name="idx_attr_effective_entity",
            ),
        ),
        migrations.AddConstraint(
            model_name="entityattributeeffectivecurrent",
            constraint=models.UniqueConstraint(
                fields=("tenant", "entity", "attribute_definition"),
                name="uq_attr_effective_current",
            ),
        ),
        migrations.AddConstraint(
            model_name="entityattributeeffectivecurrent",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_attr_effective_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="entityattributeeffectivecurrent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("cardinality", "single"),
                        ("status", "selected"),
                        ("value_fingerprint__isnull", False),
                        models.Q(
                            ("pk__isnull", True),
                            models.Q(
                                ("value_type", "text"),
                                ("value_text__isnull", False),
                                ("value_number__isnull", True),
                                ("value_boolean__isnull", True),
                                ("value_timestamp__isnull", True),
                                ("value_entity__isnull", True),
                                ("value_json__isnull", True),
                            ),
                            models.Q(
                                ("value_type", "number"),
                                ("value_text__isnull", True),
                                ("value_number__isnull", False),
                                ("value_boolean__isnull", True),
                                ("value_timestamp__isnull", True),
                                ("value_entity__isnull", True),
                                ("value_json__isnull", True),
                            ),
                            models.Q(
                                ("value_type", "boolean"),
                                ("value_text__isnull", True),
                                ("value_number__isnull", True),
                                ("value_boolean__isnull", False),
                                ("value_timestamp__isnull", True),
                                ("value_entity__isnull", True),
                                ("value_json__isnull", True),
                            ),
                            models.Q(
                                ("value_type", "timestamp"),
                                ("value_text__isnull", True),
                                ("value_number__isnull", True),
                                ("value_boolean__isnull", True),
                                ("value_timestamp__isnull", False),
                                ("value_entity__isnull", True),
                                ("value_json__isnull", True),
                            ),
                            models.Q(
                                ("value_type", "entity_reference"),
                                ("value_text__isnull", True),
                                ("value_number__isnull", True),
                                ("value_boolean__isnull", True),
                                ("value_timestamp__isnull", True),
                                ("value_entity__isnull", False),
                                ("value_json__isnull", True),
                            ),
                            models.Q(
                                ("value_type", "structured"),
                                ("value_text__isnull", True),
                                ("value_number__isnull", True),
                                ("value_boolean__isnull", True),
                                ("value_timestamp__isnull", True),
                                ("value_entity__isnull", True),
                                ("value_json__isnull", False),
                            ),
                            _connector="OR",
                        ),
                    ),
                    models.Q(
                        models.Q(("cardinality", "single"), ("status", "selected"), _negated=True),
                        ("value_fingerprint__isnull", True),
                        ("value_text__isnull", True),
                        ("value_number__isnull", True),
                        ("value_boolean__isnull", True),
                        ("value_timestamp__isnull", True),
                        ("value_entity__isnull", True),
                        ("value_json__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="ck_attr_effective_shape",
            ),
        ),
        migrations.AddIndex(
            model_name="entityattributeeffectivedirty",
            index=models.Index(fields=["queued_at", "id"], name="idx_attr_effective_dirty_queue"),
        ),
        migrations.AddConstraint(
            model_name="entityattributeeffectivedirty",
            constraint=models.UniqueConstraint(
                fields=("tenant", "entity", "attribute_definition"), name="uq_attr_effective_dirty"
            ),
        ),
        migrations.AddConstraint(
            model_name="entityattributeeffectivemembercurrent",
            constraint=models.UniqueConstraint(
                fields=("tenant", "effective", "member_key"), name="uq_attr_effective_member"
            ),
        ),
        migrations.AddConstraint(
            model_name="entityattributeeffectivemembercurrent",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_attr_effective_member_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="entityattributeeffectivemembercurrent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("pk__isnull", True),
                    models.Q(
                        ("value_type", "text"),
                        ("value_text__isnull", False),
                        ("value_number__isnull", True),
                        ("value_boolean__isnull", True),
                        ("value_timestamp__isnull", True),
                        ("value_entity__isnull", True),
                        ("value_json__isnull", True),
                    ),
                    models.Q(
                        ("value_type", "number"),
                        ("value_text__isnull", True),
                        ("value_number__isnull", False),
                        ("value_boolean__isnull", True),
                        ("value_timestamp__isnull", True),
                        ("value_entity__isnull", True),
                        ("value_json__isnull", True),
                    ),
                    models.Q(
                        ("value_type", "boolean"),
                        ("value_text__isnull", True),
                        ("value_number__isnull", True),
                        ("value_boolean__isnull", False),
                        ("value_timestamp__isnull", True),
                        ("value_entity__isnull", True),
                        ("value_json__isnull", True),
                    ),
                    models.Q(
                        ("value_type", "timestamp"),
                        ("value_text__isnull", True),
                        ("value_number__isnull", True),
                        ("value_boolean__isnull", True),
                        ("value_timestamp__isnull", False),
                        ("value_entity__isnull", True),
                        ("value_json__isnull", True),
                    ),
                    models.Q(
                        ("value_type", "entity_reference"),
                        ("value_text__isnull", True),
                        ("value_number__isnull", True),
                        ("value_boolean__isnull", True),
                        ("value_timestamp__isnull", True),
                        ("value_entity__isnull", False),
                        ("value_json__isnull", True),
                    ),
                    models.Q(
                        ("value_type", "structured"),
                        ("value_text__isnull", True),
                        ("value_number__isnull", True),
                        ("value_boolean__isnull", True),
                        ("value_timestamp__isnull", True),
                        ("value_entity__isnull", True),
                        ("value_json__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="ck_attr_effective_member_typed_value",
            ),
        ),
        migrations.AddConstraint(
            model_name="entityattributeeffectiveclaimsupport",
            constraint=models.UniqueConstraint(
                fields=("tenant", "effective", "effective_member", "claim"),
                name="uq_attr_effective_claim_support",
                nulls_distinct=False,
            ),
        ),
    ]
