# Generated by Django 5.1.15 on 2026-08-04 15:23

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("operations", "0108_attribute_effective_projection"),
    ]

    operations: ClassVar[list] = [
        migrations.CreateModel(
            name="EntityAttributeEffectiveEvidence",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("entity_id", models.UUIDField()),
                ("entity_class", models.CharField(max_length=80)),
                ("attribute_key", models.CharField(max_length=120)),
                ("attribute_display_name", models.CharField(max_length=160)),
                ("sensitivity", models.CharField(max_length=16)),
                ("cardinality", models.CharField(max_length=12)),
                ("status", models.CharField(max_length=20)),
                ("selection_reason", models.CharField(max_length=40)),
                ("value_display", models.TextField()),
                ("conflict", models.BooleanField()),
                ("projected_at", models.DateTimeField()),
            ],
            options={
                "db_table": "v_entity_attribute_effective_current",
                "managed": False,
            },
        ),
    ]
