# Generated by Django 5.1.15 on 2026-08-04 16:25

import uuid
from typing import ClassVar

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("operations", "0109_entityattributeeffectiveevidence"),
    ]

    operations: ClassVar[list] = [
        migrations.CreateModel(
            name="RelationshipType",
            fields=[
                ("key", models.CharField(max_length=120, primary_key=True, serialize=False)),
                ("display_name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "source_cardinality",
                    models.CharField(
                        choices=[("one", "One"), ("many", "Many")], default="many", max_length=8
                    ),
                ),
                (
                    "target_cardinality",
                    models.CharField(
                        choices=[("one", "One"), ("many", "Many")], default="many", max_length=8
                    ),
                ),
                ("directed", models.BooleanField(default=True)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "source_entity_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_relationship_types",
                        to="operations.entityclass",
                    ),
                ),
                (
                    "target_entity_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_relationship_types",
                        to="operations.entityclass",
                    ),
                ),
            ],
            options={
                "db_table": "relationship_types",
                "ordering": ("key",),
            },
        ),
        migrations.CreateModel(
            name="EntityRelationshipEvidenceCurrent",
            fields=[
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("native_record_type", models.CharField(max_length=80)),
                ("external_relationship_id", models.TextField()),
                (
                    "source_endpoint_source_hint",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "source_external_namespace",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "source_parent_external_namespace",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("source_parent_external_id", models.TextField(blank=True, default="")),
                ("source_external_id", models.TextField()),
                (
                    "target_endpoint_source_hint",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "target_external_namespace",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "target_parent_external_namespace",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("target_parent_external_id", models.TextField(blank=True, default="")),
                ("target_external_id", models.TextField()),
                (
                    "resolution_status",
                    models.CharField(
                        choices=[
                            ("unresolved", "Unresolved"),
                            ("partial", "Partially resolved"),
                            ("resolved", "Resolved"),
                            ("invalid", "Invalid source reference"),
                        ],
                        default="unresolved",
                        max_length=16,
                    ),
                ),
                ("authority_eligible", models.BooleanField(default=False)),
                ("authority_tier", models.PositiveSmallIntegerField(default=0)),
                ("authority_priority", models.PositiveSmallIntegerField(default=0)),
                ("material_hash", models.BinaryField()),
                ("active", models.BooleanField(default=True)),
                ("first_observed_at", models.DateTimeField()),
                ("last_observed_at", models.DateTimeField()),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source_endpoint_source_instance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relationship_source_endpoints",
                        to="operations.sourceinstance",
                    ),
                ),
                (
                    "source_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_relationship_evidence",
                        to="operations.entity",
                    ),
                ),
                (
                    "source_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relationship_evidence",
                        to="operations.sourceinstance",
                    ),
                ),
                (
                    "target_endpoint_source_instance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relationship_target_endpoints",
                        to="operations.sourceinstance",
                    ),
                ),
                (
                    "target_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_relationship_evidence",
                        to="operations.entity",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="operations.tenant"
                    ),
                ),
                (
                    "relationship_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="current_evidence",
                        to="operations.relationshiptype",
                    ),
                ),
            ],
            options={
                "db_table": "entity_relationship_evidence_current",
            },
        ),
        migrations.CreateModel(
            name="EntityRelationshipDirty",
            fields=[
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("queued_at", models.DateTimeField()),
                ("reason", models.CharField(max_length=40)),
                (
                    "source_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dirty_outgoing_relationships",
                        to="operations.entity",
                    ),
                ),
                (
                    "target_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dirty_incoming_relationships",
                        to="operations.entity",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="operations.tenant"
                    ),
                ),
                (
                    "relationship_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dirty_edges",
                        to="operations.relationshiptype",
                    ),
                ),
            ],
            options={
                "db_table": "entity_relationship_dirty",
            },
        ),
        migrations.CreateModel(
            name="EntityRelationshipDecisionCurrent",
            fields=[
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[("include", "Include"), ("exclude", "Exclude")], max_length=12
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("reason", models.TextField()),
                ("decided_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                (
                    "decided_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relationship_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_relationship_decisions",
                        to="operations.entity",
                    ),
                ),
                (
                    "target_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_relationship_decisions",
                        to="operations.entity",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="operations.tenant"
                    ),
                ),
                (
                    "relationship_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operator_decisions",
                        to="operations.relationshiptype",
                    ),
                ),
            ],
            options={
                "db_table": "entity_relationship_decision_current",
            },
        ),
        migrations.CreateModel(
            name="EntityRelationshipCurrent",
            fields=[
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suppressed", "Suppressed"),
                            ("no_evidence", "No eligible evidence"),
                        ],
                        max_length=16,
                    ),
                ),
                ("selection_reason", models.CharField(max_length=40)),
                (
                    "selected_authority_tier",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "selected_authority_priority",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("input_hash", models.BinaryField()),
                ("projected_at", models.DateTimeField()),
                (
                    "source_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="effective_outgoing_relationships",
                        to="operations.entity",
                    ),
                ),
                (
                    "target_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="effective_incoming_relationships",
                        to="operations.entity",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="operations.tenant"
                    ),
                ),
                (
                    "relationship_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="effective_edges",
                        to="operations.relationshiptype",
                    ),
                ),
            ],
            options={
                "db_table": "entity_relationships",
            },
        ),
        migrations.CreateModel(
            name="SourceEvent",
            fields=[
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("external_event_id", models.TextField()),
                ("event_type", models.CharField(max_length=120)),
                ("event_at", models.DateTimeField()),
                ("received_at", models.DateTimeField()),
                (
                    "subject_external_namespace",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "subject_parent_external_namespace",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("subject_parent_external_id", models.TextField(blank=True, default="")),
                ("subject_external_id", models.TextField(blank=True, default="")),
                ("source_actor_id", models.TextField(blank=True, default="")),
                ("source_actor_display", models.JSONField(blank=True, default=dict)),
                ("outcome", models.CharField(blank=True, default="", max_length=80)),
                ("raw_event", models.JSONField()),
                ("raw_hash", models.BinaryField()),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("recorded", "Recorded"),
                            ("confirmed", "Confirmed withdrawal"),
                            ("unresolved", "Unresolved subject"),
                            ("out_of_order", "Out of order"),
                            ("invalid", "Invalid"),
                        ],
                        default="recorded",
                        max_length=20,
                    ),
                ),
                ("processing_reason", models.CharField(blank=True, default="", max_length=120)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source_binding",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_events",
                        to="operations.sourcebinding",
                    ),
                ),
                (
                    "source_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_events",
                        to="operations.sourceinstance",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="operations.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "source_events",
            },
        ),
        migrations.AddField(
            model_name="entityobservationhistory",
            name="closed_by_source_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="closed_observation_history",
                to="operations.sourceevent",
            ),
        ),
        migrations.CreateModel(
            name="EntityRelationshipEvidenceSupport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "evidence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="effective_support",
                        to="operations.entityrelationshipevidencecurrent",
                    ),
                ),
                (
                    "relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_support",
                        to="operations.entityrelationshipcurrent",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="operations.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "entity_relationship_evidence_support",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "relationship", "evidence"),
                        name="uq_relationship_evidence_support",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RelationshipAuthorityPolicy",
            fields=[
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("native_record_type", models.CharField(max_length=80)),
                ("eligible", models.BooleanField(default=False)),
                ("authority_tier", models.PositiveSmallIntegerField(default=0)),
                ("priority", models.PositiveSmallIntegerField(default=0)),
                ("enabled", models.BooleanField(default=True)),
                ("reason", models.CharField(blank=True, default="", max_length=160)),
                (
                    "source_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relationship_authority_policies",
                        to="operations.sourceinstance",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="operations.tenant"
                    ),
                ),
                (
                    "relationship_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authority_policies",
                        to="operations.relationshiptype",
                    ),
                ),
            ],
            options={
                "db_table": "relationship_authority_policies",
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "tenant",
                            "source_instance",
                            "native_record_type",
                            "relationship_type",
                        ),
                        name="uq_relationship_authority_policy",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="entityrelationshipevidencecurrent",
            index=models.Index(
                fields=["tenant", "relationship_type", "resolution_status", "active"],
                name="idx_rel_evidence_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="entityrelationshipevidencecurrent",
            constraint=models.UniqueConstraint(
                fields=("tenant", "source_instance", "external_relationship_id"),
                name="uq_relationship_evidence_source_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="entityrelationshipevidencecurrent",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_relationship_evidence_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="entityrelationshipevidencecurrent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("source_external_id", ""), _negated=True),
                    models.Q(("target_external_id", ""), _negated=True),
                    models.Q(
                        models.Q(
                            ("source_parent_external_namespace", ""),
                            ("source_parent_external_id", ""),
                        ),
                        models.Q(
                            models.Q(("source_parent_external_namespace", ""), _negated=True),
                            models.Q(("source_parent_external_id", ""), _negated=True),
                        ),
                        _connector="OR",
                    ),
                    models.Q(
                        models.Q(
                            ("target_parent_external_namespace", ""),
                            ("target_parent_external_id", ""),
                        ),
                        models.Q(
                            models.Q(("target_parent_external_namespace", ""), _negated=True),
                            models.Q(("target_parent_external_id", ""), _negated=True),
                        ),
                        _connector="OR",
                    ),
                ),
                name="ck_relationship_evidence_endpoints",
            ),
        ),
        migrations.AddConstraint(
            model_name="entityrelationshipevidencecurrent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("active", True), ("withdrawn_at__isnull", True)),
                    models.Q(("active", False), ("withdrawn_at__isnull", False)),
                    _connector="OR",
                ),
                name="ck_relationship_evidence_presence",
            ),
        ),
        migrations.AddIndex(
            model_name="entityrelationshipdirty",
            index=models.Index(fields=["queued_at", "id"], name="idx_relationship_dirty_queue"),
        ),
        migrations.AddConstraint(
            model_name="entityrelationshipdirty",
            constraint=models.UniqueConstraint(
                fields=("tenant", "relationship_type", "source_entity", "target_entity"),
                name="uq_entity_relationship_dirty",
            ),
        ),
        migrations.AddConstraint(
            model_name="entityrelationshipdecisioncurrent",
            constraint=models.UniqueConstraint(
                fields=("tenant", "relationship_type", "source_entity", "target_entity"),
                name="uq_relationship_decision_current",
            ),
        ),
        migrations.AddConstraint(
            model_name="entityrelationshipdecisioncurrent",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_relationship_decision_tenant_id"
            ),
        ),
        migrations.AddIndex(
            model_name="entityrelationshipcurrent",
            index=models.Index(
                fields=["tenant", "relationship_type", "status"],
                name="idx_entity_relationship_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="entityrelationshipcurrent",
            constraint=models.UniqueConstraint(
                fields=("tenant", "relationship_type", "source_entity", "target_entity"),
                name="uq_entity_relationship_current",
            ),
        ),
        migrations.AddConstraint(
            model_name="entityrelationshipcurrent",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_entity_relationship_tenant_id"
            ),
        ),
        migrations.AddIndex(
            model_name="sourceevent",
            index=models.Index(
                fields=["tenant", "source_instance", "event_type", "event_at"],
                name="idx_source_events_type_time",
            ),
        ),
        migrations.AddIndex(
            model_name="sourceevent",
            index=models.Index(
                fields=["tenant", "processing_status", "event_at"],
                name="idx_source_events_processing",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceevent",
            constraint=models.UniqueConstraint(
                fields=("tenant", "source_instance", "external_event_id"),
                name="uq_source_events_external_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceevent",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_source_events_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("subject_parent_external_namespace", ""),
                        ("subject_parent_external_id", ""),
                    ),
                    models.Q(
                        models.Q(("subject_parent_external_namespace", ""), _negated=True),
                        models.Q(("subject_parent_external_id", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="ck_source_event_parent_identity",
            ),
        ),
    ]
