# Generated by Django 5.1.15 on 2026-08-04 16:39

import uuid
from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("operations", "0111_relationship_candidate_event_contracts"),
    ]

    operations: ClassVar[list] = [
        migrations.CreateModel(
            name="EntityRelationshipEvidenceHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("endpoint_identity", models.JSONField()),
                (
                    "resolution_status",
                    models.CharField(
                        choices=[
                            ("unresolved", "Unresolved"),
                            ("partial", "Partially resolved"),
                            ("resolved", "Resolved"),
                            ("invalid", "Invalid source reference"),
                        ],
                        max_length=16,
                    ),
                ),
                ("authority_eligible", models.BooleanField(default=False)),
                ("authority_tier", models.PositiveSmallIntegerField(default=0)),
                ("authority_priority", models.PositiveSmallIntegerField(default=0)),
                ("material_hash", models.BinaryField()),
                ("effective_from", models.DateTimeField()),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                (
                    "evidence_current",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="history",
                        to="operations.entityrelationshipevidencecurrent",
                    ),
                ),
                (
                    "relationship_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_history",
                        to="operations.relationshiptype",
                    ),
                ),
                (
                    "source_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_relationship_evidence_history",
                        to="operations.entity",
                    ),
                ),
                (
                    "target_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_relationship_evidence_history",
                        to="operations.entity",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="operations.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "entity_relationship_evidence_history",
                "indexes": [
                    models.Index(
                        fields=["tenant", "effective_from"], name="idx_rel_evidence_hist_from"
                    ),
                    models.Index(
                        fields=["tenant", "effective_to"], name="idx_rel_evidence_hist_to"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("effective_to__isnull", True)),
                        fields=("tenant", "evidence_current"),
                        name="uq_relationship_evidence_history_open",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("effective_to__isnull", True),
                            ("effective_to__gt", models.F("effective_from")),
                            _connector="OR",
                        ),
                        name="ck_relationship_evidence_history_window",
                    ),
                ],
            },
        ),
    ]
