# Generated by Django 5.1.15 on 2026-08-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0124_drop_legacy_matviews'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mergecandidate',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('tenant', 'canonical_key'), name='uq_merge_candidates_open_canonical_key'),
        ),
    ]
