# Generated by Django 5.1.15 on 2026-09-08 15:26

import uuid
from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models

FORWARD_SQL = r"""
INSERT INTO operations.entity_classes (name, display_name, description)
VALUES (
    'os_installation', 'OS installation',
    'A client-owned operating-system installation that may run on different Computers.'
)
ON CONFLICT (name) DO UPDATE
    SET display_name = EXCLUDED.display_name,
        description = EXCLUDED.description;

INSERT INTO operations.entity_class_scopes (entity_class_id, scope_kind)
VALUES ('os_installation', 'client')
ON CONFLICT (entity_class_id, scope_kind) DO NOTHING;

INSERT INTO operations.relationship_types (
    key, display_name, description, source_entity_class_id,
    target_entity_class_id, source_cardinality, target_cardinality,
    directed, enabled
) VALUES (
    'os_installation_runs_on_computer', 'OS installation runs on Computer',
    'A client-owned OS installation is currently hosted by one Computer.',
    'os_installation', 'device', 'one', 'many', TRUE, TRUE
)
ON CONFLICT (key) DO UPDATE
    SET display_name = EXCLUDED.display_name,
        description = EXCLUDED.description,
        source_entity_class_id = EXCLUDED.source_entity_class_id,
        target_entity_class_id = EXCLUDED.target_entity_class_id,
        source_cardinality = EXCLUDED.source_cardinality,
        target_cardinality = EXCLUDED.target_cardinality,
        directed = EXCLUDED.directed,
        enabled = EXCLUDED.enabled;

ALTER TABLE operations.operating_system_installations
    ADD CONSTRAINT fk_os_installation_tenant_entity
    FOREIGN KEY (tenant_id, entity_id)
    REFERENCES operations.entities (tenant_id, id)
    DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_os_installation_tenant_client
    FOREIGN KEY (tenant_id, client_id)
    REFERENCES operations.clients (tenant_id, id)
    DEFERRABLE INITIALLY DEFERRED;

CREATE OR REPLACE FUNCTION operations.validate_os_installation_entity()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = operations, pg_temp
AS $function$
DECLARE
    anchor operations.entities%ROWTYPE;
BEGIN
    SELECT * INTO anchor
      FROM operations.entities
     WHERE tenant_id = NEW.tenant_id AND id = NEW.entity_id;
    IF anchor.id IS NULL
       OR anchor.entity_class_id <> 'os_installation'
       OR anchor.scope_kind <> 'client'
       OR anchor.client_id IS DISTINCT FROM NEW.client_id THEN
        RAISE EXCEPTION 'OS installation entity must be a client-scoped os_installation anchor';
    END IF;
    RETURN NEW;
END;
$function$;

CREATE TRIGGER validate_os_installation_entity
BEFORE INSERT OR UPDATE ON operations.operating_system_installations
FOR EACH ROW EXECUTE FUNCTION operations.validate_os_installation_entity();

ALTER TABLE operations.operating_system_installation_source_identities
    ADD CONSTRAINT fk_os_installation_identity_tenant_installation
    FOREIGN KEY (tenant_id, installation_id)
    REFERENCES operations.operating_system_installations (tenant_id, id)
    DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_os_installation_identity_tenant_source
    FOREIGN KEY (tenant_id, source_instance_id)
    REFERENCES operations.source_instances (tenant_id, id)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE operations.operating_system_installations ENABLE ROW LEVEL SECURITY;
ALTER TABLE operations.operating_system_installations FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON operations.operating_system_installations
    USING (tenant_id = operations.current_tenant_id())
    WITH CHECK (tenant_id = operations.current_tenant_id());

ALTER TABLE operations.operating_system_installation_source_identities ENABLE ROW LEVEL SECURITY;
ALTER TABLE operations.operating_system_installation_source_identities FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON operations.operating_system_installation_source_identities
    USING (tenant_id = operations.current_tenant_id())
    WITH CHECK (tenant_id = operations.current_tenant_id());

REVOKE ALL ON operations.operating_system_installations,
    operations.operating_system_installation_source_identities
FROM PUBLIC, operations_app, ninja_ingest, operations_readonly, metabase_ro;
GRANT SELECT, INSERT, UPDATE ON operations.operating_system_installations,
    operations.operating_system_installation_source_identities TO ninja_ingest;
GRANT SELECT ON operations.operating_system_installations,
    operations.operating_system_installation_source_identities
TO operations_app, operations_readonly, operations_view_owner;

INSERT INTO operations.relationship_authority_policies (
    id, tenant_id, version, source_instance_id, native_record_type,
    relationship_type_id, eligible, authority_tier, priority, enabled, reason
)
SELECT gen_random_uuid(), source_instance.tenant_id, 1, source_instance.id,
       'agent_observation', 'os_installation_runs_on_computer',
       TRUE, 100, 100, TRUE,
       'Agent record directly observes its OS installation running on a Computer.'
  FROM operations.source_instances source_instance
ON CONFLICT (tenant_id, source_instance_id, native_record_type, relationship_type_id)
DO NOTHING;

CREATE VIEW operations.v_computer_os_installation_current
WITH (security_barrier = true) AS
SELECT relationship.tenant_id,
       computer.id AS device_id,
       installation.id AS installation_id,
       installation.entity_id AS installation_entity_id,
       installation.first_observed_at,
       installation.last_observed_at,
       relationship.projected_at
  FROM operations.entity_relationships relationship
  JOIN operations.devices computer
    ON computer.tenant_id = relationship.tenant_id
   AND computer.entity_id = relationship.target_entity_id
  JOIN operations.operating_system_installations installation
    ON installation.tenant_id = relationship.tenant_id
   AND installation.entity_id = relationship.source_entity_id
 WHERE relationship.tenant_id = operations.current_tenant_id()
   AND relationship.relationship_type_id = 'os_installation_runs_on_computer'
   AND relationship.status = 'active';

ALTER VIEW operations.v_computer_os_installation_current OWNER TO operations_view_owner;
REVOKE ALL ON operations.v_computer_os_installation_current
FROM PUBLIC, operations_app, ninja_ingest, operations_readonly, metabase_ro;
GRANT SELECT ON operations.v_computer_os_installation_current
TO operations_app, operations_readonly;
REVOKE ALL ON FUNCTION operations.validate_os_installation_entity()
FROM PUBLIC, operations_app, ninja_ingest, operations_readonly, metabase_ro;
ALTER FUNCTION operations.validate_os_installation_entity() OWNER TO operations_migrate;
"""


REVERSE_SQL = r"""
DROP POLICY IF EXISTS tenant_isolation ON operations.operating_system_installation_source_identities;
DROP POLICY IF EXISTS tenant_isolation ON operations.operating_system_installations;
DROP VIEW IF EXISTS operations.v_computer_os_installation_current;
DROP TRIGGER IF EXISTS validate_os_installation_entity ON operations.operating_system_installations;
DROP FUNCTION IF EXISTS operations.validate_os_installation_entity();
ALTER TABLE operations.operating_system_installation_source_identities
    DROP CONSTRAINT IF EXISTS fk_os_installation_identity_tenant_source,
    DROP CONSTRAINT IF EXISTS fk_os_installation_identity_tenant_installation;
ALTER TABLE operations.operating_system_installations
    DROP CONSTRAINT IF EXISTS fk_os_installation_tenant_client,
    DROP CONSTRAINT IF EXISTS fk_os_installation_tenant_entity;
DELETE FROM operations.relationship_authority_policies
 WHERE native_record_type = 'agent_observation'
   AND relationship_type_id = 'os_installation_runs_on_computer';
DELETE FROM operations.relationship_types
 WHERE key = 'os_installation_runs_on_computer';
DELETE FROM operations.entity_class_scopes
 WHERE entity_class_id = 'os_installation';
DELETE FROM operations.entity_classes
 WHERE name = 'os_installation';
"""


class Migration(migrations.Migration):
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("operations", "0152_device_observation_current_read_model"),
    ]

    operations: ClassVar[list] = [
        migrations.CreateModel(
            name="OperatingSystemInstallation",
            fields=[
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("first_observed_at", models.DateTimeField()),
                ("last_observed_at", models.DateTimeField()),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                ("retired_reason", models.CharField(blank=True, default="", max_length=120)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operating_system_installations",
                        to="operations.client",
                    ),
                ),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operating_system_installation_record",
                        to="operations.entity",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="operations.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "operating_system_installations",
            },
        ),
        migrations.CreateModel(
            name="OperatingSystemInstallationSourceIdentity",
            fields=[
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("external_namespace", models.CharField(max_length=120)),
                (
                    "parent_external_namespace",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("parent_external_id", models.TextField(blank=True, default="")),
                ("external_id", models.TextField()),
                ("first_observed_at", models.DateTimeField()),
                ("last_observed_at", models.DateTimeField()),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_identities",
                        to="operations.operatingsysteminstallation",
                    ),
                ),
                (
                    "source_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operating_system_installation_identities",
                        to="operations.sourceinstance",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="operations.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "operating_system_installation_source_identities",
            },
        ),
        migrations.AddIndex(
            model_name="operatingsysteminstallation",
            index=models.Index(
                fields=["tenant", "client", "retired_at"], name="idx_os_installation_current"
            ),
        ),
        migrations.AddConstraint(
            model_name="operatingsysteminstallation",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_os_installation_tenant_id"
            ),
        ),
        migrations.AddIndex(
            model_name="operatingsysteminstallationsourceidentity",
            index=models.Index(
                fields=["tenant", "installation"], name="idx_os_installation_identity"
            ),
        ),
        migrations.AddConstraint(
            model_name="operatingsysteminstallationsourceidentity",
            constraint=models.UniqueConstraint(
                fields=(
                    "tenant",
                    "source_instance",
                    "external_namespace",
                    "parent_external_namespace",
                    "parent_external_id",
                    "external_id",
                ),
                name="uq_os_installation_source_identity",
            ),
        ),
        migrations.RunSQL(FORWARD_SQL, REVERSE_SQL),
    ]
