"""Root URL configuration."""

from __future__ import annotations

from django.contrib import admin
from django.urls import path
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)

from apps.core.views import (
    admin_finding_acknowledge,
    client_candidate_accept,
    client_candidate_detail,
    client_candidate_exclude,
    client_candidate_fix,
    client_candidate_map,
    client_candidates_queue,
    client_profile_assign,
    client_policy_delete,
    client_policy_edit,
    client_policy_new,
    client_switch,
    device_detail,
    device_patch_scope_clear,
    device_patch_scope_set,
    finding_acknowledge,
    finding_resolve,
    finding_snooze,
    finding_suppress,
    findings_bulk_action,
    findings_admin_health,
    findings_queue,
    fleet_coverage,
    healthz,
    home,
    identity_candidate_confirm,
    identity_candidate_reject,
    identity_candidates_list,
    merge_candidates_queue,
    notification_rule_toggle,
    notification_rules_list,
    notification_suppressions_list,
    org_devices,
    requirement_profiles_list,
    software_decision_create,
    software_decisions_queue,
    org_index,
    org_policies,
    org_software,
    org_software_decide,
    org_software_devices,
    devices_page,
    patching_queue,
    search,
    software_page,
    sources_status,
)

urlpatterns = [
    path("", home, name="home"),
    path("healthz", healthz, name="healthz"),
    path("orgs/<slug:org_slug>/", org_index, name="org_index"),
    path("orgs/<slug:org_slug>/devices/", org_devices, name="org_devices"),
    path("orgs/<slug:org_slug>/devices/<uuid:device_id>/", device_detail, name="device_detail"),
    path("orgs/<slug:org_slug>/devices/<uuid:device_id>/patch-scope/set/", device_patch_scope_set, name="device_patch_scope_set"),
    path("orgs/<slug:org_slug>/devices/<uuid:device_id>/patch-scope/clear/", device_patch_scope_clear, name="device_patch_scope_clear"),
    path("orgs/<slug:org_slug>/policies/", org_policies, name="org_policies"),
    path("orgs/<slug:org_slug>/policies/new/", client_policy_new, name="client_policy_new"),
    path("orgs/<slug:org_slug>/policies/<uuid:policy_id>/edit/", client_policy_edit, name="client_policy_edit"),
    path("orgs/<slug:org_slug>/policies/<uuid:policy_id>/delete/", client_policy_delete, name="client_policy_delete"),
    path("orgs/<slug:org_slug>/software/", org_software, name="org_software"),
    path("orgs/<slug:org_slug>/software/devices/", org_software_devices, name="org_software_devices"),
    path("orgs/<slug:org_slug>/software/decide/", org_software_decide, name="org_software_decide"),
    path("findings/", findings_queue, name="findings_queue"),
    path("patching/", patching_queue, name="patching_queue"),
    path("software/", software_page, name="software_page"),
    path("devices/", devices_page, name="devices_page"),
    path("search/", search, name="search"),
    path("findings/<uuid:finding_id>/ack/", finding_acknowledge, name="finding_acknowledge"),
    path("findings/<uuid:finding_id>/resolve/", finding_resolve, name="finding_resolve"),
    path("findings/<uuid:finding_id>/snooze/", finding_snooze, name="finding_snooze"),
    path("findings/<uuid:finding_id>/suppress/", finding_suppress, name="finding_suppress"),
    path("findings/bulk/", findings_bulk_action, name="findings_bulk_action"),
    path("admin/findings/health/", findings_admin_health, name="findings_admin_health"),
    path("admin/findings/<uuid:finding_id>/ack/", admin_finding_acknowledge, name="admin_finding_acknowledge"),
    path("coverage/", fleet_coverage, name="fleet_coverage"),
    path("sources/", sources_status, name="sources_status"),
    path("merge-candidates/", merge_candidates_queue, name="merge_candidates_queue"),
    path("clients/candidates/", client_candidates_queue, name="client_candidates_queue"),
    path("clients/candidates/<uuid:candidate_id>/", client_candidate_detail, name="client_candidate_detail"),
    path("clients/candidates/<uuid:candidate_id>/accept", client_candidate_accept, name="client_candidate_accept"),
    path("clients/candidates/<uuid:candidate_id>/map", client_candidate_map, name="client_candidate_map"),
    path("clients/candidates/<uuid:candidate_id>/exclude", client_candidate_exclude, name="client_candidate_exclude"),
    path("clients/candidates/<uuid:candidate_id>/fix", client_candidate_fix, name="client_candidate_fix"),
    path("admin/notifications/", notification_rules_list, name="notification_rules_list"),
    path("admin/notifications/rules/<uuid:rule_id>/toggle", notification_rule_toggle, name="notification_rule_toggle"),
    path("admin/notifications/suppressions/", notification_suppressions_list, name="notification_suppressions_list"),
    path("admin/requirement-profiles/", requirement_profiles_list, name="requirement_profiles_list"),
    path("software/decisions/", software_decisions_queue, name="software_decisions_queue"),
    path("software/decisions/create", software_decision_create, name="software_decision_create"),
    path("admin/identity/", identity_candidates_list, name="identity_candidates_list"),
    path("admin/identity/<uuid:candidate_id>/confirm", identity_candidate_confirm, name="identity_candidate_confirm"),
    path("admin/identity/<uuid:candidate_id>/reject", identity_candidate_reject, name="identity_candidate_reject"),
    path("orgs/<slug:org_slug>/profile/", client_profile_assign, name="client_profile_assign"),
    path("switch/", client_switch, name="client_switch"),
    path("admin/", admin.site.urls),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("api/docs/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger-ui"),
    path("api/redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
]
