"""Root URL configuration."""

from __future__ import annotations

from django.contrib import admin
from django.urls import path
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)

from apps.core.generic_admin import (
    entity_admin_detail,
    entity_admin_list,
    entity_candidate_attach,
    entity_candidate_detail,
    entity_candidate_reject,
    entity_candidates_queue,
)
from apps.core.views import (
    admin_finding_acknowledge,
    admin_jobs,
    admin_jobs_run,
    admin_jobs_run_all,
    classifier_config,
    client_candidate_accept,
    client_candidate_detail,
    client_candidate_exclude,
    client_candidate_fix,
    client_candidate_map,
    client_candidates_queue,
    client_policy_delete,
    client_policy_edit,
    client_policy_new,
    client_profile_assign,
    client_requirements_config,
    client_switch,
    device_detail,
    device_exemption_add,
    device_exemption_clear,
    device_merge,
    device_patch_scope_clear,
    device_patch_scope_set,
    device_status_config,
    devices_page,
    finding_acknowledge,
    finding_resolve,
    finding_snooze,
    finding_suppress,
    findings_admin_health,
    findings_bulk_action,
    findings_queue,
    fleet_coverage,
    healthz,
    home,
    lifecycle_policy_status,
    merge_candidates_queue,
    notification_rule_toggle,
    notification_rules_list,
    notification_suppressions_list,
    operations_admin_overview,
    org_devices,
    org_index,
    org_policies,
    org_software,
    org_software_decide,
    org_software_devices,
    patch_activity_search_page,
    patch_evidence_page,
    patch_trends_page,
    patching_queue,
    requirement_profiles_list,
    search,
    software_decision_bulk,
    software_decision_create,
    software_decision_log,
    software_decisions_queue,
    software_detail,
    software_page,
    software_products,
    software_publisher_detail,
    software_publishers,
    software_tech_checklist,
    software_title_lookup,
    software_user_risk,
    sources_status,
)

urlpatterns = [
    path("", home, name="home"),
    path("healthz", healthz, name="healthz"),
    path("orgs/<slug:org_slug>/", org_index, name="org_index"),
    path("orgs/<slug:org_slug>/devices/", org_devices, name="org_devices"),
    path("orgs/<slug:org_slug>/devices/<uuid:device_id>/", device_detail, name="device_detail"),
    path(
        "orgs/<slug:org_slug>/devices/<uuid:device_id>/patch-scope/set/",
        device_patch_scope_set,
        name="device_patch_scope_set",
    ),
    path(
        "orgs/<slug:org_slug>/devices/<uuid:device_id>/patch-scope/clear/",
        device_patch_scope_clear,
        name="device_patch_scope_clear",
    ),
    path(
        "orgs/<slug:org_slug>/devices/<uuid:device_id>/exemption/add/",
        device_exemption_add,
        name="device_exemption_add",
    ),
    path(
        "orgs/<slug:org_slug>/devices/<uuid:device_id>/exemption/clear/",
        device_exemption_clear,
        name="device_exemption_clear",
    ),
    path(
        "orgs/<slug:org_slug>/devices/<uuid:device_id>/merge/<uuid:target_id>/",
        device_merge,
        name="device_merge",
    ),
    path("orgs/<slug:org_slug>/policies/", org_policies, name="org_policies"),
    path("orgs/<slug:org_slug>/policies/new/", client_policy_new, name="client_policy_new"),
    path(
        "orgs/<slug:org_slug>/policies/<uuid:policy_id>/edit/",
        client_policy_edit,
        name="client_policy_edit",
    ),
    path(
        "orgs/<slug:org_slug>/policies/<uuid:policy_id>/delete/",
        client_policy_delete,
        name="client_policy_delete",
    ),
    path("orgs/<slug:org_slug>/software/", org_software, name="org_software"),
    path(
        "orgs/<slug:org_slug>/software/devices/", org_software_devices, name="org_software_devices"
    ),
    path("orgs/<slug:org_slug>/software/decide/", org_software_decide, name="org_software_decide"),
    path("findings/", findings_queue, name="findings_queue"),
    path("patching/", patching_queue, name="patching_queue"),
    path("patching/evidence/", patch_evidence_page, name="patch_evidence_page"),
    path("patching/trends/", patch_trends_page, name="patch_trends_page"),
    path("patching/activity/", patch_activity_search_page, name="patch_activity_search_page"),
    path("software/", software_page, name="software_page"),
    path("software/products/", software_products, name="software_products"),
    # Path converter so canonical names containing slashes still resolve.
    path("software/title/<path:name>/", software_detail, name="software_detail"),
    path("software/publishers/", software_publishers, name="software_publishers"),
    path(
        "software/publishers/<path:publisher>/",
        software_publisher_detail,
        name="software_publisher_detail",
    ),
    path("software/tech-checklist/", software_tech_checklist, name="software_tech_checklist"),
    path("software/user-risk/", software_user_risk, name="software_user_risk"),
    path(
        "software/title/<path:name>/lookup/<str:source>/",
        software_title_lookup,
        name="software_title_lookup",
    ),
    path("software/decisions/bulk/", software_decision_bulk, name="software_decision_bulk"),
    path("software/decisions/log/", software_decision_log, name="software_decision_log"),
    path("admin/jobs/", admin_jobs, name="admin_jobs"),
    path("admin/jobs/run/<str:job_id>/", admin_jobs_run, name="admin_jobs_run"),
    path("admin/jobs/run-all/", admin_jobs_run_all, name="admin_jobs_run_all"),
    path("devices/", devices_page, name="devices_page"),
    path("search/", search, name="search"),
    path("findings/<uuid:finding_id>/ack/", finding_acknowledge, name="finding_acknowledge"),
    path("findings/<uuid:finding_id>/resolve/", finding_resolve, name="finding_resolve"),
    path("findings/<uuid:finding_id>/snooze/", finding_snooze, name="finding_snooze"),
    path("findings/<uuid:finding_id>/suppress/", finding_suppress, name="finding_suppress"),
    path("findings/bulk/", findings_bulk_action, name="findings_bulk_action"),
    path("admin/findings/health/", findings_admin_health, name="findings_admin_health"),
    path(
        "admin/findings/<uuid:finding_id>/ack/",
        admin_finding_acknowledge,
        name="admin_finding_acknowledge",
    ),
    path("coverage/", fleet_coverage, name="fleet_coverage"),
    path("sources/", sources_status, name="sources_status"),
    path("merge-candidates/", merge_candidates_queue, name="merge_candidates_queue"),
    path("clients/candidates/", client_candidates_queue, name="client_candidates_queue"),
    path(
        "clients/candidates/<uuid:candidate_id>/",
        client_candidate_detail,
        name="client_candidate_detail",
    ),
    path(
        "clients/candidates/<uuid:candidate_id>/accept",
        client_candidate_accept,
        name="client_candidate_accept",
    ),
    path(
        "clients/candidates/<uuid:candidate_id>/map",
        client_candidate_map,
        name="client_candidate_map",
    ),
    path(
        "clients/candidates/<uuid:candidate_id>/exclude",
        client_candidate_exclude,
        name="client_candidate_exclude",
    ),
    path(
        "clients/candidates/<uuid:candidate_id>/fix",
        client_candidate_fix,
        name="client_candidate_fix",
    ),
    path("admin/notifications/", notification_rules_list, name="notification_rules_list"),
    path(
        "admin/notifications/rules/<uuid:rule_id>/toggle",
        notification_rule_toggle,
        name="notification_rule_toggle",
    ),
    path(
        "admin/notifications/suppressions/",
        notification_suppressions_list,
        name="notification_suppressions_list",
    ),
    path(
        "admin/requirement-profiles/", requirement_profiles_list, name="requirement_profiles_list"
    ),
    path("admin/overview/", operations_admin_overview, name="operations_admin_overview"),
    path("admin/entities/", entity_admin_list, name="entity_admin_list"),
    path(
        "admin/entities/<uuid:entity_id>/",
        entity_admin_detail,
        name="entity_admin_detail",
    ),
    path(
        "admin/entity-candidates/",
        entity_candidates_queue,
        name="entity_candidates_queue",
    ),
    path(
        "admin/entity-candidates/<uuid:candidate_id>/",
        entity_candidate_detail,
        name="entity_candidate_detail",
    ),
    path(
        "admin/entity-candidates/<uuid:candidate_id>/attach/",
        entity_candidate_attach,
        name="entity_candidate_attach",
    ),
    path(
        "admin/entity-candidates/<uuid:candidate_id>/reject/",
        entity_candidate_reject,
        name="entity_candidate_reject",
    ),
    path("admin/classifier/", classifier_config, name="classifier_config"),
    path("admin/device-status/", device_status_config, name="device_status_config"),
    path("admin/lifecycle/", lifecycle_policy_status, name="lifecycle_policy_status"),
    path("software/decisions/", software_decisions_queue, name="software_decisions_queue"),
    path("software/decisions/create", software_decision_create, name="software_decision_create"),
    path("orgs/<slug:org_slug>/profile/", client_profile_assign, name="client_profile_assign"),
    path(
        "orgs/<slug:org_slug>/configuration/",
        client_requirements_config,
        name="client_requirements_config",
    ),
    path("switch/", client_switch, name="client_switch"),
    path("admin/", admin.site.urls),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("api/docs/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger-ui"),
    path("api/redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
]
